// SDK独立门禁：准确提交、上游来源、自有改动和适用测试均失败关闭。
import { execFileSync, spawnSync } from 'node:child_process';
import { lstatSync, readFileSync, realpathSync, existsSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const shaPattern = /^[0-9a-f]{40}$/u;
const registry = 'registry+https://github.com/rust-lang/crates.io-index';
const remoteWork = '/home/runner/work/_temp/polkadot-sdk-tatagate';
const rustRoot = '/home/runner/.rustup/toolchains/1.97.1-x86_64-unknown-linux-gnu';
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
const offlineConfig = packages => '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
  + JSON.stringify(packages) + '\n';

// 只接受Cargo生成的这两份锁的有限语法；遇到其它来源或新语法先失败，不能漏读包。
export function lockedPackages(text) {
  const blocks = text.split(/^\[\[package\]\]\n/mu);
  if (!/^# This file is automatically @generated by Cargo\.\n# It is not intended for manual editing\.\nversion = [34]\n\n$/u.test(blocks.shift()) || !blocks.length) {
    throw new Error('SDK依赖锁格式无效');
  }
  const result = new Map();
  for (const block of blocks) {
    const fields = new Map(); let dependencies = false;
    for (const line of block.trimEnd().split('\n')) {
      if (!line) continue;
      if (dependencies) {
        if (line === ']') dependencies = false;
        else if (!/^ "[A-Za-z0-9_+. ():/#?=&%-]+",$/u.test(line)) throw new Error('SDK依赖锁列表格式无效');
        continue;
      }
      if (line === 'dependencies = [') { if (fields.has('dependencies')) throw new Error('SDK依赖锁字段重复'); fields.set('dependencies', true); dependencies = true; continue; }
      const match = line.match(/^(name|version|source|checksum) = "([^"\\\r\n]+)"$/u);
      if (!match || fields.has(match[1])) throw new Error('SDK依赖锁字段无效');
      fields.set(match[1], match[2]);
    }
    const name = fields.get('name'), version = fields.get('version'), source = fields.get('source'), checksum = fields.get('checksum');
    if (dependencies || !/^[A-Za-z0-9_-]+$/u.test(name ?? '') || !/^\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.+-]+)?$/u.test(version ?? '')) throw new Error('SDK依赖锁坐标无效');
    if (!source) { if (checksum) throw new Error('SDK本地包带有registry摘要'); continue; }
    if (source !== registry || !/^[0-9a-f]{64}$/u.test(checksum ?? '')) throw new Error('SDK依赖来源或摘要无效');
    const coordinate = name + '-' + version;
    if (result.has(coordinate) && result.get(coordinate).checksum !== checksum) throw new Error('SDK依赖重复坐标异摘要');
    result.set(coordinate, { name, version, checksum });
  }
  return result;
}
export function lockedUnion(...locks) {
  const union = new Map();
  for (const lock of locks) for (const [coordinate, value] of lockedPackages(lock)) {
    if (union.has(coordinate) && union.get(coordinate).checksum !== value.checksum) throw new Error('SDK联合锁重复坐标异摘要');
    union.set(coordinate, value);
  }
  return union;
}
function exactDirectory(path) {
  if (typeof path !== 'string' || !path.startsWith('/') || resolve(path) !== path || realpathSync(path) !== path || !lstatSync(path).isDirectory()) throw new Error('SDK准备目录不是准确物理目录');
  const before = lstatSync(path);
  return () => { const after = lstatSync(path); if (realpathSync(path) !== path || !after.isDirectory() || before.dev !== after.dev || before.ino !== after.ino) throw new Error('SDK准备目录被替换'); };
}
function exactFile(path) {
  if (realpathSync(path) !== path || !lstatSync(path).isFile() || lstatSync(path).nlink !== 1) throw new Error('SDK准备文件不是独占普通文件');
  return readFileSync(path);
}

// 正式入口固定官方Ubuntu Runner及本仓push，测试只能通过函数参数提供受控事实。
export function remoteContext(root, work, input, { expectedWork = remoteWork, platform = process.platform,
  arch = process.arch, os = readFileSync('/etc/os-release', 'utf8'), event = JSON.parse(readFileSync(input.GITHUB_EVENT_PATH, 'utf8')) } = {}) {
  if (platform !== 'linux' || arch !== 'x64' || !/^ID=ubuntu$/mu.test(os) || !/^VERSION_ID="24\.04"$/mu.test(os)
    || input.GITHUB_ACTIONS !== 'true' || input.RUNNER_ENVIRONMENT !== 'github-hosted'
    || input.RUNNER_OS !== 'Linux' || input.RUNNER_ARCH !== 'X64' || input.GITHUB_EVENT_NAME !== 'push'
    || input.GITHUB_REPOSITORY !== 'crcfrcn/polkadot-sdk' || input.GITHUB_REF !== 'refs/heads/main'
    || event.repository?.full_name !== input.GITHUB_REPOSITORY || event.ref !== input.GITHUB_REF
    || event.after !== input.GITHUB_SHA) throw new Error('SDK远端准备Runner或事件身份不符');
  gateRange(event.before, event.after);
  exactDirectory(root); exactDirectory(work);
  if (work !== expectedWork || input.TATAGATE_WORK !== work || input.GITHUB_WORKSPACE !== root || realpathSync(input.GITHUB_WORKSPACE) !== root
    || work === root || work.startsWith(root + '/') || root.startsWith(work + '/')) throw new Error('SDK远端准备工作根越界');
  return event;
}
export function remoteTools(root, work, input, { execute = command, expectedRust = rustRoot,
  expectedNode = '/opt/hostedtoolcache/node/25.2.1/x64/bin/node', expectedClang = '/usr/lib/llvm-18/bin/clang',
  expectedCMake = '/usr/local/bin/cmake', expectedLibclang = '/usr/lib/llvm-18/lib' } = {}) {
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER',
    'RUSTUP_TOOLCHAIN', 'WASM_BUILD_TOOLCHAIN', 'PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN']) {
    if (Object.hasOwn(input, key)) throw new Error('SDK远端准备拒绝跳过或替换工具：' + key);
  }
  const check = (path, args, pattern) => {
    exactFile(path);
    if (!(lstatSync(path).mode & 0o111) || !pattern.test(execute(path, args, root, input))) throw new Error('SDK远端工具版本不符');
  };
  const cargo = join(expectedRust, 'bin/cargo'), rustc = join(expectedRust, 'bin/rustc');
  if (input.CARGO !== cargo || input.TATAGATE_CARGO !== cargo || input.RUSTC !== rustc || input.TATAGATE_RUSTC !== rustc
    || input.RUSTDOC !== join(expectedRust, 'bin/rustdoc') || input.TATAGATE_NODE !== expectedNode
    || input.CC !== expectedClang || input.CXX !== join(dirname(expectedClang), 'clang++') || realpathSync(input.CXX) !== expectedClang
    || input.CMAKE_COMMAND !== expectedCMake || input.LIBCLANG_PATH !== expectedLibclang
    || input.PROTOC !== join(work, 'tools/protoc/bin/protoc')
    || input.PRODUCT_GIT_BIN !== join(work, 'tools/git/payload/bin/git')
    || input.TATAGATE_ACTIONLINT !== join(work, 'tools/actionlint/actionlint')
    || input.CARGO_BUILD_JOBS !== '2' || input.CARGO_PROFILE_DEV_DEBUG !== '0' || input.CARGO_PROFILE_TEST_DEBUG !== '0'
    || input.CARGO_INCREMENTAL !== '0') throw new Error('SDK远端工具对象交付不符');
  check(expectedNode, ['--version'], /^v25\.2\.1$/u);
  check(cargo, ['--version'], /^cargo 1\.97\.1 /u); check(rustc, ['--version'], /^rustc 1\.97\.1 /u);
  check(input.RUSTDOC, ['--version'], /^rustdoc 1\.97\.1 /u);
  check(expectedClang, ['--version'], /^(?:Ubuntu |Debian )?clang version 18\.1\.3(?: |\n)/u);
  check(expectedCMake, ['--version'], /^cmake version 3\.31\.6(?:\n|$)/u);
  exactDirectory(expectedLibclang);
  if (!lstatSync(realpathSync(join(expectedLibclang, 'libclang.so.1'))).isFile()) throw new Error('SDK远端libclang缺失');
  check(input.PROTOC, ['--version'], /^libprotoc 35\.0$/u);
  check(input.PRODUCT_GIT_BIN, ['--version'], /^git version 2\.54\.0$/u);
  check(input.TATAGATE_ACTIONLINT, ['--version'], /^1\.7\.12(?:\n|$)/u);
  check(join(work, 'tools/solidity/bin/solc'), ['--version'], /\nVersion: 0\.8\.30\+commit\.73712a01\.Linux\.g\+\+$/u);
  check(join(work, 'tools/solidity/bin/resolc'), ['--version'], /^Solidity frontend for the revive compiler version 1\.0\.0\+commit\.[a-f0-9]+\.llvm-\d+\.\d+\.\d+$/u);
  return join(expectedRust, 'lib/rustlib/src/rust/library');
}

// Cargo负责官方下载与解包，这里另验锁、原包摘要、目录完整清单和每个展开文件。
export function verifyVendor(packages, downloadHome, union) {
  const stablePackages = exactDirectory(packages), stableHome = exactDirectory(downloadHome);
  const expected = [...union.keys()].sort();
  if (JSON.stringify(readdirSync(packages).sort()) !== JSON.stringify(expected)) throw new Error('SDK离线包目录清单不符');
  const cache = join(downloadHome, 'registry/cache'), stableCache = exactDirectory(cache);
  const registries = readdirSync(cache);
  if (registries.length !== 1 || !/^index\.crates\.io-[a-f0-9]+$/u.test(registries[0])) throw new Error('SDK下载registry缓存来源不符');
  const archiveRoot = join(cache, registries[0]), stableArchives = exactDirectory(archiveRoot);
  if (JSON.stringify(readdirSync(archiveRoot).sort()) !== JSON.stringify(expected.map(value => value + '.crate').sort())) throw new Error('SDK原包清单不符');
  for (const [coordinate, value] of union) {
    if (digest(exactFile(join(archiveRoot, coordinate + '.crate'))) !== value.checksum) throw new Error('SDK锁定原包摘要不符：' + coordinate);
    const directory = join(packages, coordinate), stable = exactDirectory(directory);
    const checksum = JSON.parse(exactFile(join(directory, '.cargo-checksum.json')));
    if (checksum.package !== value.checksum || !checksum.files || Array.isArray(checksum.files) || typeof checksum.files !== 'object') throw new Error('SDK目录源包摘要不符：' + coordinate);
    const files = [];
    const directories = new Set();
    for (const path of Object.keys(checksum.files)) {
      gatePath(path); const parts = path.split('/'); parts.pop();
      while (parts.length) { directories.add(parts.join('/') + '/'); parts.pop(); }
    }
    const walk = (path, prefix = '') => {
      if (prefix && !directories.has(prefix)) throw new Error('SDK展开目录完整清单不符：' + coordinate);
      const unchanged = exactDirectory(path);
      for (const entry of readdirSync(path)) {
        const relative = prefix + entry, absolute = join(path, entry), stat = lstatSync(absolute);
        gatePath(relative);
        if (stat.isDirectory()) walk(absolute, relative + '/');
        else { exactFile(absolute); if (relative !== '.cargo-checksum.json') files.push(relative); }
      }
      unchanged();
    };
    walk(directory);
    if (JSON.stringify(files.sort()) !== JSON.stringify(Object.keys(checksum.files).sort())) throw new Error('SDK展开文件完整清单不符：' + coordinate);
    for (const [path, hash] of Object.entries(checksum.files)) {
      gatePath(path);
      if (!/^[0-9a-f]{64}$/u.test(hash) || digest(exactFile(join(directory, path))) !== hash) throw new Error('SDK展开文件摘要不符：' + coordinate);
    }
    stable();
  }
  stablePackages(); stableHome(); stableCache(); stableArchives();
}
export function prepareOffline(root, work, input, library, { execute = command,
  expectedSDK = '96b19cb91b15ce8348e9933fcaf35392b95b7a1d03764c7a19d4cb00cf329e05',
  expectedStd = '02120dd57c4c5fd70c81fd92472681c8de5cc2dd78258276da37bb2253666061', expectedCount = 1556 } = {}) {
  const stableRoot = exactDirectory(root), stableWork = exactDirectory(work), stableLibrary = exactDirectory(library);
  if (root === work || root.startsWith(work + '/') || work.startsWith(root + '/')) throw new Error('SDK离线准备根越界');
  const sdkLock = join(root, 'Cargo.lock'), stdLock = join(library, 'Cargo.lock');
  const sdkBytes = exactFile(sdkLock), stdBytes = exactFile(stdLock);
  if (digest(sdkBytes) !== expectedSDK || digest(stdBytes) !== expectedStd) throw new Error('SDK准备锁不在获准闭包');
  const union = lockedUnion(sdkBytes.toString('utf8'), stdBytes.toString('utf8'));
  if (union.size !== expectedCount) throw new Error('SDK联合闭包数量不符');
  const downloadHome = join(work, 'cargo-download/home'), home = join(work, 'cargo/home'), packages = join(work, 'cargo/packages');
  // 整个准备区域只能创建一次，已有目录不能被本轮接管。
  mkdirSync(join(work, 'cargo-download')); mkdirSync(downloadHome);
  mkdirSync(join(work, 'cargo')); mkdirSync(home);
  const stableDownload = exactDirectory(downloadHome), stableCargo = exactDirectory(join(work, 'cargo')), stableHome = exactDirectory(home);
  const environment = { ...input, CARGO_HOME: downloadHome, CARGO_NET_OFFLINE: 'false', CARGO_NET_RETRY: '0', RUSTC_BOOTSTRAP: '1',
    CARGO_REGISTRIES_CRATES_IO_INDEX: 'sparse+https://index.crates.io/', CARGO_REGISTRIES_CRATES_IO_PROTOCOL: 'sparse' };
  writeFileSync(join(downloadHome, 'config.toml'), '[net]\nretry = 0\n\n[source.crates-io]\nregistry = "sparse+https://index.crates.io/"\n', { flag: 'wx' });
  execute(input.CARGO, ['vendor', '--locked', '--versioned-dirs', '--manifest-path', join(root, 'Cargo.toml'),
    '--sync', join(library, 'Cargo.toml'), packages], root, environment);
  stableRoot(); stableWork(); stableLibrary(); stableDownload(); stableCargo(); stableHome();
  if (!exactFile(sdkLock).equals(sdkBytes) || !exactFile(stdLock).equals(stdBytes)) throw new Error('SDK准备期间原锁变化');
  verifyVendor(packages, downloadHome, union);
  writeFileSync(join(home, 'config.toml'), offlineConfig(packages), { flag: 'wx' });
  stableRoot(); stableWork(); stableLibrary(); stableCargo(); stableHome();
  if (!exactFile(sdkLock).equals(sdkBytes) || !exactFile(stdLock).equals(stdBytes)) throw new Error('SDK离线配置交付期间原锁变化');
  return { ...input, CARGO_HOME: home };
}

export function hostChecks(paths) {
  if (!paths.includes('substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs')) return [];
  return [['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface-test', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--doc']];
}
export function gateRange(base, head) {
  if (!shaPattern.test(base ?? '') || !shaPattern.test(head ?? '') || base === head) throw new Error('SDK门禁提交区间无效');
  return { base, head };
}
export function gateContract(value) {
  if (value?.schema !== 1 || value.repository !== 'polkadot-sdk' || value.upstream !== 'paritytech/polkadot-sdk'
    || !shaPattern.test(value.upstream_base ?? '') || !shaPattern.test(value.initial_sha ?? '')
    || !Array.isArray(value.checks) || value.checks.join(',') !== 'identity,history,source,workflow,tests,changed-crates') {
    throw new Error('SDK门禁合同无效');
  }
  return value;
}
export function gatePath(value) {
  if (!value || value.startsWith('/') || value.includes('\\') || value.split('/').some(part => ['', '.', '..'].includes(part))) {
    throw new Error('SDK门禁路径越界');
  }
  return value;
}
function command(file, args, root, environment = process.env) {
  if (!file || !file.startsWith('/') || realpathSync(file) !== file
    || !lstatSync(file).isFile() || !(lstatSync(file).mode & 0o111)) throw new Error('SDK门禁缺少准确工具路径');
  const result = spawnSync(file, args, { cwd: root, env: environment, encoding: 'utf8', timeout: 3_600_000,
    // SDK完整metadata当前约13MiB，保留有界缓冲以容纳完整依赖图。
    stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024 });
  if (result.status !== 0 || result.error) {
    process.stderr.write((result.stderr ?? '').slice(-64 * 1024));
    throw new Error('SDK门禁工具检查失败：' + args.slice(0, 4).join(' ') + '；退出码 ' + result.status
      + (result.error ? '；' + result.error.message : ''));
  }
  return result.stdout.trim();
}

// 门禁只使用调用方已准备的离线目录源；完整夹具和Runtime构建不能跳过。
export function gateEnvironment(root, work, input, { canonical = realpathSync, stat = lstatSync, execute = command } = {}) {
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER',
    'RUSTUP_TOOLCHAIN', 'WASM_BUILD_TOOLCHAIN', 'PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN']) {
    if (Object.hasOwn(input, key)) throw new Error('SDK完整门禁拒绝跳过或替换工具：' + key);
  }
  const regular = path => typeof path === 'string' && path.startsWith('/') && resolve(path) === path
    && canonical(path) === path && stat(path).isFile() && !!(stat(path).mode & 0o111);
  const cargo = input.TATAGATE_CARGO, rustc = input.TATAGATE_RUSTC;
  if (!regular(cargo) || !regular(rustc) || dirname(cargo) !== dirname(rustc)
    || input.RUSTC !== rustc || input.CARGO !== cargo
    || execute(rustc, ['--version'], root, input).split(' ')[1] !== '1.97.1'
    || execute(cargo, ['--version'], root, input).split(' ')[1] !== '1.97.1') throw new Error('SDK门禁Rust对象或版本不符');
  if (!work || !work.startsWith('/') || resolve(work) !== work || work === root || work.startsWith(root + '/')
    || canonical(work) !== work || !stat(work).isDirectory()) throw new Error('SDK检查中间物目录无效');
  const home = input.CARGO_HOME;
  const boundary = dirname(root) === dirname(work) ? dirname(work) : work;
  if (typeof home !== 'string' || !home.startsWith(boundary + '/') || home.startsWith(root + '/')
    || canonical(home) !== home || !stat(home).isDirectory()) throw new Error('SDK门禁缺少独立离线Cargo主目录');
  const config = join(home, 'config.toml');
  if (canonical(config) !== config || !stat(config).isFile()) throw new Error('SDK门禁离线配置不是准确文件');
  const text = readFileSync(config, 'utf8');
  const directory = text.match(/^directory = (".*")$/mu)?.[1];
  const packages = directory && JSON.parse(directory);
  if (!/^\[net\]\noffline = true\n\n\[source\.crates-io\]\nreplace-with = "verified"\n\n\[source\.verified\]\ndirectory = "[^\n]+"\n$/u.test(text)
    || typeof packages !== 'string' || !packages.startsWith(boundary + '/') || packages.startsWith(root + '/')
    || canonical(packages) !== packages || !stat(packages).isDirectory()) throw new Error('SDK门禁缺少完整离线目录源');
  return { ...input, RUSTC: rustc, CARGO: cargo, CARGO_NET_OFFLINE: 'true',
    CARGO_TARGET_DIR: join(work, 'cargo-target'), RUSTC_BOOTSTRAP: '1', WASM_BUILD_STD: '1',
    // OUT_DIR位于独立临时目录，WASM子工程必须明确继承受检源码的原锁。
    WASM_BUILD_WORKSPACE_HINT: root };
}
function git(root, args) {
  const tool = process.env.PRODUCT_GIT_BIN;
  if (!tool || realpathSync(tool) !== tool || !lstatSync(tool).isFile()) throw new Error('SDK门禁缺少准确Git');
  if (command(tool, ['--version'], root) !== 'git version 2.54.0') throw new Error('SDK门禁Git版本不符');
  return execFileSync(tool, ['-C', root, ...args], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024,
    env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' }, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}
function identity(root, physical = false) {
  if (realpathSync(root) !== root || !lstatSync(root + '/.git').isDirectory()
    || git(root, ['rev-parse', '--show-toplevel']) !== root
    || git(root, ['remote', 'get-url', 'origin']) !== 'https://github.com/crcfrcn/polkadot-sdk.git') throw new Error('SDK门禁仓库身份无效');
  if (physical && (root !== '/Users/rhett/polkadot-sdk' || git(root, ['branch', '--show-current']) !== 'main'
    || git(root, ['remote', 'get-url', 'upstream']) !== 'https://github.com/paritytech/polkadot-sdk.git')) throw new Error('SDK正式开发入口无效');
}
function checkedSource(root, path) {
  const absolute = resolve(root, gatePath(path));
  if (!absolute.startsWith(root + '/') || realpathSync(absolute) !== absolute || !lstatSync(absolute).isFile()) throw new Error('SDK源码不是准确文件');
  const text = readFileSync(absolute, 'utf8');
  if (/-----BEGIN [A-Z ]*PRIVATE KEY-----|github_pat_[A-Za-z0-9_]{20,}|ghs_[A-Za-z0-9_]{20,}/u.test(text)
    || /\/Users\/[A-Za-z0-9_-]+\/(?:tataconsole|GMB|TATA|TUYU)\//u.test(text)) throw new Error('SDK源码包含机密或私有工作区路径');
}
export function runGate(root, baseSHA, headSHA, work) {
  root = resolve(root); identity(root); const range = gateRange(baseSHA, headSHA);
  const contract = gateContract(JSON.parse(readFileSync(join(root, '.github/tatagate/contracts.json'), 'utf8')));
  if (git(root, ['rev-parse', 'HEAD']) !== range.head || git(root, ['status', '--porcelain=v1', '--untracked-files=all']) !== '') throw new Error('SDK门禁快照不一致');
  git(root, ['merge-base', '--is-ancestor', range.base, range.head]);
  git(root, ['merge-base', '--is-ancestor', contract.initial_sha, range.head]);
  git(root, ['merge-base', '--is-ancestor', contract.upstream_base, contract.initial_sha]);
  git(root, ['diff', '--check', range.base, range.head]);
  const paths = git(root, ['diff', '--name-only', '-z', range.base, range.head]).split('\u0000').filter(Boolean);
  const crates = new Set();
  for (const path of paths) {
    gatePath(path);
    const absolute = join(root, path);
    if (!existsSync(absolute)) continue;
    checkedSource(root, path);
    if (path.startsWith('.github/workflows/') && /\.ya?ml$/u.test(path)) {
      command(process.env.TATAGATE_ACTIONLINT, ['-shellcheck=', '-pyflakes=', path], root);
    }
    if (path.endsWith('.rs') || path.endsWith('Cargo.toml')) {
      let directory = dirname(absolute);
      while (directory !== root && directory.startsWith(root + '/')) {
        const manifest = join(directory, 'Cargo.toml');
        if (existsSync(manifest)) {
          const source = readFileSync(manifest, 'utf8');
          const packageBlock = source.match(/\[package\]([\s\S]*?)(?=\n\[|$)/u)?.[1];
          const name = packageBlock?.match(/^name\s*=\s*"([a-z0-9-]+)"/mu)?.[1];
          if (name) { crates.add(name); break; }
        }
        directory = dirname(directory);
      }
    }
  }
  command(process.execPath, ['--test', '.github/tatagate/test.mjs'], root);
  const hosts = hostChecks(paths);
  if (crates.size || hosts.length || paths.includes('Cargo.lock') || paths.includes('Cargo.toml')) {
    const environment = gateEnvironment(root, work, process.env), cargo = environment.CARGO;
    command(cargo, ['metadata', '--locked', '--offline', '--format-version', '1'], root, environment);
    for (const name of crates) {
      command(cargo, ['check', '--locked', '--offline', '-p', name], root, environment);
      command(cargo, ['test', '--locked', '--offline', '-p', name, '--lib'], root, environment);
    }
    for (const args of hosts) command(cargo, args, root, environment);
    // workspace声明与锁整体改动需要全工作空间检查，不能只验证门禁自身。
    if (paths.includes('Cargo.lock') || paths.includes('Cargo.toml')) command(cargo, ['check', '--locked', '--offline', '--workspace'], root, environment);
  }
  return { repository: 'polkadot-sdk', base_sha: range.base, head_sha: range.head, changed_crates: [...crates].sort() };
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const [mode, ...args] = process.argv.slice(2);
    if (mode === 'physical' && args.length === 1) identity(resolve(args[0]), true);
    else if (mode === 'local' && args.length === 4) console.log(JSON.stringify(runGate(args[0], args[1], args[2], args[3])));
    else if (['prepare', 'remote'].includes(mode) && args.length === 0) {
      const root = realpathSync(process.cwd()), work = process.env.TATAGATE_WORK;
      const event = remoteContext(root, work, process.env);
      identity(root);
      if (git(root, ['rev-parse', 'HEAD']) !== event.after || git(root, ['status', '--porcelain=v1', '--untracked-files=all']) !== '') throw new Error('SDK远端准备源码提交不符');
      const library = remoteTools(root, work, process.env);
      if (process.execPath !== process.env.TATAGATE_NODE) throw new Error('SDK远端Node执行对象不符');
      if (mode === 'prepare') {
        const environment = prepareOffline(root, work, process.env, library);
        gateEnvironment(root, work, environment);
        console.log(JSON.stringify({ repository: 'polkadot-sdk', head_sha: event.after, packages: 1556, cargo_home: environment.CARGO_HOME }));
      } else {
        if (process.env.CARGO_HOME !== join(work, 'cargo/home')) throw new Error('SDK远端离线主目录不符');
        const sdkLock = exactFile(join(root, 'Cargo.lock')), stdLock = exactFile(join(library, 'Cargo.lock'));
        if (digest(sdkLock) !== '96b19cb91b15ce8348e9933fcaf35392b95b7a1d03764c7a19d4cb00cf329e05'
          || digest(stdLock) !== '02120dd57c4c5fd70c81fd92472681c8de5cc2dd78258276da37bb2253666061') throw new Error('SDK远端原锁不在获准闭包');
        const union = lockedUnion(sdkLock.toString('utf8'), stdLock.toString('utf8'));
        if (union.size !== 1556) throw new Error('SDK远端联合闭包数量不符');
        verifyVendor(join(work, 'cargo/packages'), join(work, 'cargo-download/home'), union);
        console.log(JSON.stringify(runGate(root, event.before, event.after, work)));
      }
    } else throw new Error('SDK门禁参数无效');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
