import {readFileSync as tataGateRead, realpathSync as tataGateReal} from 'node:fs';
import {execFileSync as tataGateExec} from 'node:child_process';
export const tataGateOwner = "crcfrcn/polkadot-sdk";
// SDK独立门禁：准确提交、上游来源、自有改动和适用测试均失败关闭。
import { execFileSync, spawnSync } from 'node:child_process';
import { lstatSync, readFileSync, realpathSync, existsSync, readdirSync, mkdirSync, writeFileSync, cpSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname, join, isAbsolute, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {Readable} from 'node:stream';
import {spec} from 'node:test/reporters';

const shaPattern = /^[0-9a-f]{40}$/u;
const registry = 'registry+https://github.com/rust-lang/crates.io-index';
const rustRoot = '/home/runner/.rustup/toolchains/1.97.1-x86_64-unknown-linux-gnu';
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
const offlineConfig = packages => '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
  + JSON.stringify(packages) + '\n';


// Git依赖只接受无凭据GitHub HTTPS仓库及同一40位提交，不接受分支、标签或异源。
export function lockedGitSource(source) {
  if (typeof source !== 'string' || !/^git\+https:\/\/github\.com\/[A-Za-z0-9][A-Za-z0-9-]*\/[A-Za-z0-9][A-Za-z0-9._-]*\.git\?rev=[a-f0-9]{40}#[a-f0-9]{40}$/u.test(source)) throw new Error('SDK固定Git来源无效');
  const url = new URL(source.slice(4)), revision = url.searchParams.get('rev');
  if (url.href !== source.slice(4) || url.username || url.password || url.hash !== '#' + revision) throw new Error('SDK固定Git提交不一致');
  return { repository: url.origin + url.pathname, revision };
}
const registryUnion = union => new Map([...union].filter(([, value]) => !value.source));

// 只接受Cargo生成的两份锁和准确固定Git来源；未知语法先失败，不能漏读包。
export function lockedPackages(text) {
  const blocks = text.split(/^\[\[package\]\]\n/mu);
  if (!/^# This file is automatically @generated by Cargo\.\n# It is not intended for manual editing\.\nversion = [34]\n\n$/u.test(blocks.shift()) || !blocks.length) {
    throw new Error('SDK依赖锁格式无效');
  }
  const result = new Map();
  for (const block of blocks) {
    const fields = new Map(); let dependencies = false;
    for (const line of block.trimEnd().split('\n')) {
      if (!line) continue;
      if (dependencies) {
        if (line === ']') dependencies = false;
        else if (!/^ "[A-Za-z0-9_+. ():/#?=&%-]+",$/u.test(line)) throw new Error('SDK依赖锁列表格式无效');
        continue;
      }
      if (line === 'dependencies = [') { if (fields.has('dependencies')) throw new Error('SDK依赖锁字段重复'); fields.set('dependencies', true); dependencies = true; continue; }
      const match = line.match(/^(name|version|source|checksum) = "([^"\\\r\n]+)"$/u);
      if (!match || fields.has(match[1])) throw new Error('SDK依赖锁字段无效');
      fields.set(match[1], match[2]);
    }
    const name = fields.get('name'), version = fields.get('version'), source = fields.get('source'), checksum = fields.get('checksum');
    if (dependencies || !/^[A-Za-z0-9_-]+$/u.test(name ?? '') || !/^\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.+-]+)?$/u.test(version ?? '')) throw new Error('SDK依赖锁坐标无效');
    if (!source) { if (checksum) throw new Error('SDK本地包带有registry摘要'); continue; }
    const coordinate = name + '-' + version;
    let value;
    if (source === registry) {
      if (!/^[0-9a-f]{64}$/u.test(checksum ?? '')) throw new Error('SDK依赖来源或摘要无效');
      value = { name, version, checksum };
    } else {
      lockedGitSource(source);
      if (checksum) throw new Error('SDK Git包不得伪造registry摘要');
      value = { name, version, source };
    }
    const prior = result.get(coordinate);
    if (prior && (prior.checksum !== value.checksum || prior.source !== value.source)) throw new Error('SDK依赖重复坐标异摘要或异源');
    result.set(coordinate, value);
  }
  return result;
}
export function lockedUnion(...locks) {
  const union = new Map();
  for (const lock of locks) for (const [coordinate, value] of lockedPackages(lock)) {
    if (union.has(coordinate) && (union.get(coordinate).checksum !== value.checksum || union.get(coordinate).source !== value.source)) throw new Error('SDK联合锁重复坐标异摘要或异源');
    union.set(coordinate, value);
  }
  return union;
}
function exactDirectory(path) {
  if (typeof path !== 'string' || !path.startsWith('/') || resolve(path) !== path || realpathSync(path) !== path || !lstatSync(path).isDirectory()) throw new Error('SDK准备目录不是准确物理目录');
  const before = lstatSync(path);
  return () => { const after = lstatSync(path); if (realpathSync(path) !== path || !after.isDirectory() || before.dev !== after.dev || before.ino !== after.ino) throw new Error('SDK准备目录被替换'); };
}
function exactFile(path) {
  if (realpathSync(path) !== path || !lstatSync(path).isFile() || lstatSync(path).nlink !== 1) throw new Error('SDK准备文件不是独占普通文件：' + path);
  return readFileSync(path);
}

// 正式入口固定官方Ubuntu Runner及本仓push，测试只能通过函数参数提供受控事实。
export function remoteContext(root, work, input, { expectedWork = join(root,'target/test/tatagate'), platform = process.platform,
  arch = process.arch, os = readFileSync('/etc/os-release', 'utf8'), event = JSON.parse(readFileSync(input.GITHUB_EVENT_PATH, 'utf8')) } = {}) {
  if (platform !== 'linux' || arch !== 'x64' || !/^ID=ubuntu$/mu.test(os) || !/^VERSION_ID="24\.04"$/mu.test(os)
    || input.GITHUB_ACTIONS !== 'true' || input.RUNNER_ENVIRONMENT !== 'github-hosted'
    || input.RUNNER_OS !== 'Linux' || input.RUNNER_ARCH !== 'X64' || input.GITHUB_EVENT_NAME !== 'push'
    || input.GITHUB_REPOSITORY !== 'crcfrcn/polkadot-sdk' || input.GITHUB_REF !== 'refs/heads/main'
    || event.repository?.full_name !== input.GITHUB_REPOSITORY || event.ref !== input.GITHUB_REF
    || event.after !== input.GITHUB_SHA) throw new Error('SDK远端准备Runner或事件身份不符');
  gateRange(event.before, event.after);
  exactDirectory(root); exactDirectory(work);
  if (work !== expectedWork || input.TATAGATE_WORK !== work || input.GITHUB_WORKSPACE !== root || realpathSync(input.GITHUB_WORKSPACE) !== root
    || work === root || !work.startsWith(join(root,'target') + '/') || root.startsWith(work + '/')) throw new Error('SDK远端准备工作根越界');
  return event;
}
export function remoteTools(root, work, input, { execute = command, expectedRust = rustRoot,
  expectedNode = '/opt/hostedtoolcache/node/25.2.1/x64/bin/node', expectedClang = '/usr/lib/llvm-18/bin/clang',
  expectedCMake = '/usr/local/bin/cmake', expectedLibclang = '/usr/lib/llvm-18/lib' } = {}) {
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER',
    'RUSTUP_TOOLCHAIN', 'WASM_BUILD_TOOLCHAIN', 'PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN',
    'RUSTFLAGS', 'CARGO_ENCODED_RUSTFLAGS']) {
    if (Object.hasOwn(input, key)) throw new Error('SDK远端准备拒绝跳过或替换工具：' + key);
  }
  const check = (path, args, pattern) => {
    exactFile(path);
    if (!(lstatSync(path).mode & 0o111) || !pattern.test(execute(path, args, root, input))) throw new Error('SDK远端工具版本不符');
  };
  const cargo = join(expectedRust, 'bin/cargo'), rustc = join(expectedRust, 'bin/rustc');
  // 原锁rustix的Linux原生目标使用官方libc后端，避免新Rust拒绝其内部属性。
  if (input.CARGO !== cargo || input.TATAGATE_CARGO !== cargo || input.RUSTC !== rustc || input.TATAGATE_RUSTC !== rustc
    || input.RUSTDOC !== join(expectedRust, 'bin/rustdoc') || input.TATAGATE_NODE !== expectedNode
    || input.CC !== expectedClang || input.CXX !== join(dirname(expectedClang), 'clang++') || realpathSync(input.CXX) !== expectedClang
    || input.CMAKE_COMMAND !== expectedCMake || input.LIBCLANG_PATH !== expectedLibclang
    || input.PROTOC !== join(work, 'tools/protoc/bin/protoc')
    || input.PRODUCT_GIT_BIN !== join(work, 'tools/git/payload/bin/git')
    || input.TATAGATE_ACTIONLINT !== join(work, 'tools/actionlint/actionlint')
    || input.CARGO_BUILD_JOBS !== '2' || input.CARGO_PROFILE_DEV_DEBUG !== '0' || input.CARGO_PROFILE_TEST_DEBUG !== '0'
    || input.CARGO_INCREMENTAL !== '0'
    || input.CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS !== '--cfg=rustix_use_libc') throw new Error('SDK远端工具对象交付不符');
  check(expectedNode, ['--version'], /^v25\.2\.1$/u);
  check(cargo, ['--version'], /^cargo 1\.97\.1 /u); check(rustc, ['--version'], /^rustc 1\.97\.1 /u);
  check(input.RUSTDOC, ['--version'], /^rustdoc 1\.97\.1 /u);
  check(expectedClang, ['--version'], /^(?:Ubuntu |Debian )?clang version 18\.1\.3(?: |\n)/u);
  check(expectedCMake, ['--version'], /^cmake version 3\.31\.6(?:\n|$)/u);
  exactDirectory(expectedLibclang);
  if (!lstatSync(realpathSync(join(expectedLibclang, 'libclang.so.1'))).isFile()) throw new Error('SDK远端libclang缺失');
  check(input.PROTOC, ['--version'], /^libprotoc 35\.0$/u);
  check(input.PRODUCT_GIT_BIN, ['--version'], /^git version 2\.54\.0$/u);
  check(input.TATAGATE_ACTIONLINT, ['--version'], /^1\.7\.12(?:\n|$)/u);
  check(join(work, 'tools/solidity/bin/solc'), ['--version'], /\nVersion: 0\.8\.30\+commit\.73712a01\.Linux\.g\+\+$/u);
  check(join(work, 'tools/solidity/bin/resolc'), ['--version'], /^Solidity frontend for the revive compiler version 1\.0\.0\+commit\.[a-f0-9]+\.llvm-\d+\.\d+\.\d+$/u);
  return join(expectedRust, 'lib/rustlib/src/rust/library');
}

// Cargo负责官方下载与解包，这里另验锁、原包摘要、目录完整清单和每个展开文件。
export function verifyVendor(packages, downloadHome, locked) {
  const union = registryUnion(locked);
  const stablePackages = exactDirectory(packages), stableHome = exactDirectory(downloadHome);
  const expected = [...union.keys()].sort();
  if (JSON.stringify(readdirSync(packages).sort()) !== JSON.stringify(expected)) throw new Error('SDK离线包目录清单不符');
  const cache = join(downloadHome, 'registry/cache'), stableCache = exactDirectory(cache);
  const registries = readdirSync(cache);
  if (registries.length !== 1 || !/^index\.crates\.io-[a-f0-9]+$/u.test(registries[0])) throw new Error('SDK下载registry缓存来源不符');
  const archiveRoot = join(cache, registries[0]), stableArchives = exactDirectory(archiveRoot);
  if (JSON.stringify(readdirSync(archiveRoot).sort()) !== JSON.stringify(expected.map(value => value + '.crate').sort())) throw new Error('SDK原包清单不符');
  for (const [coordinate, value] of union) {
    if (digest(exactFile(join(archiveRoot, coordinate + '.crate'))) !== value.checksum) throw new Error('SDK锁定原包摘要不符：' + coordinate);
    const directory = join(packages, coordinate), stable = exactDirectory(directory);
    const checksum = JSON.parse(exactFile(join(directory, '.cargo-checksum.json')));
    if (checksum.package !== value.checksum || !checksum.files || Array.isArray(checksum.files) || typeof checksum.files !== 'object') throw new Error('SDK目录源包摘要不符：' + coordinate);
    const files = [];
    const directories = new Set();
    for (const path of Object.keys(checksum.files)) {
      gatePath(path); const parts = path.split('/'); parts.pop();
      while (parts.length) { directories.add(parts.join('/') + '/'); parts.pop(); }
    }
    const walk = (path, prefix = '') => {
      if (prefix && !directories.has(prefix)) throw new Error('SDK展开目录完整清单不符：' + coordinate);
      const unchanged = exactDirectory(path);
      for (const entry of readdirSync(path)) {
        const relative = prefix + entry, absolute = join(path, entry), stat = lstatSync(absolute);
        gatePath(relative);
        if (stat.isDirectory()) walk(absolute, relative + '/');
        else { exactFile(absolute); if (relative !== '.cargo-checksum.json') files.push(relative); }
      }
      unchanged();
    };
    walk(directory);
    if (JSON.stringify(files.sort()) !== JSON.stringify(Object.keys(checksum.files).sort())) throw new Error('SDK展开文件完整清单不符：' + coordinate);
    for (const [path, hash] of Object.entries(checksum.files)) {
      gatePath(path);
      if (!/^[0-9a-f]{64}$/u.test(hash) || digest(exactFile(join(directory, path))) !== hash) throw new Error('SDK展开文件摘要不符：' + coordinate);
    }
    stable();
  }
  stablePackages(); stableHome(); stableCache(); stableArchives();
}

// Git包保持Git来源，不能把vendor目录包伪装为registry原件。实际metadata、提交和受检源码同时绑定。
export function verifyGitCache(root, home, union, input, { execute = command, metadata } = {}) {
  const expected = [...union.values()].filter(value => value.source);
  if (!expected.length) return;
  const gitRoot = join(home, 'git'); exactDirectory(gitRoot); exactDirectory(join(gitRoot, 'db'));
  const environment = { ...input, CARGO_HOME: home, CARGO_NET_OFFLINE: 'true',
    GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', GIT_NO_REPLACE_OBJECTS: '1' };
  metadata ??= JSON.parse(execute(input.CARGO, ['metadata', '--locked', '--offline', '--format-version', '1'], root, environment));
  if (!Array.isArray(metadata.packages)) throw new Error('SDK Git metadata缺少包清单');
  for (const value of expected) {
    const matches = metadata.packages.filter(pkg => pkg.name === value.name && pkg.version === value.version && pkg.source === value.source);
    if (matches.length !== 1) throw new Error('SDK Git包坐标与原锁不一致');
    const manifest = matches[0].manifest_path;
    if (typeof manifest !== 'string' || !manifest.startsWith(join(gitRoot, 'checkouts') + '/')) throw new Error('SDK Git源码不属于本次Cargo主目录');
    exactFile(manifest);
    const checkout = execute(input.PRODUCT_GIT_BIN, ['-C', dirname(manifest), 'rev-parse', '--show-toplevel'], root, environment);
    if (!checkout.startsWith(join(gitRoot, 'checkouts') + '/')) throw new Error('SDK Git检出根越界');
    exactDirectory(checkout);
    const { revision } = lockedGitSource(value.source);
    if (execute(input.PRODUCT_GIT_BIN, ['-C', checkout, 'rev-parse', 'HEAD'], root, environment) !== revision) throw new Error('SDK Git检出提交不符');
    execute(input.PRODUCT_GIT_BIN, ['-C', checkout, 'diff', '--exit-code', revision, '--'], root, environment);
    // Cargo只可增加自己的完成标记；未跟踪或被忽略源码也不能影响锁定检出。
    const extra = execute(input.PRODUCT_GIT_BIN, ['-C', checkout, 'ls-files', '--others'], root, environment);
    if (extra.split('\n').some(path => path && path !== '.cargo-ok')) throw new Error('SDK Git检出含额外文件');
  }
}

export function prepareOffline(root, work, input, library, { execute = command,
  expectedSDK = 'e87457b0d643498e75840b68b2a4a33d26ae316cc43514eae3f34f63e4fc0780',
  expectedStd = '02120dd57c4c5fd70c81fd92472681c8de5cc2dd78258276da37bb2253666061', expectedCount = 1556 } = {}) {
  const stableRoot = exactDirectory(root), stableWork = exactDirectory(work), stableLibrary = exactDirectory(library);
  if (root === work || root.startsWith(work + '/') || !work.startsWith(join(root,'target') + '/')) throw new Error('SDK离线准备根越界');
  const sdkLock = join(root, 'Cargo.lock'), stdLock = join(library, 'Cargo.lock');
  const sdkBytes = exactFile(sdkLock), stdBytes = exactFile(stdLock);
  if (digest(sdkBytes) !== expectedSDK || digest(stdBytes) !== expectedStd) throw new Error('SDK准备锁不在获准闭包');
  const union = lockedUnion(sdkBytes.toString('utf8'), stdBytes.toString('utf8'));
  if (union.size !== expectedCount) throw new Error('SDK联合闭包数量不符');
  const downloadHome = join(work, 'cargo-download/home'), home = join(work, 'cargo/home'), packages = join(work, 'cargo/packages');
  // 整个准备区域只能创建一次，已有目录不能被本轮接管。
  mkdirSync(join(work, 'cargo-download')); mkdirSync(downloadHome);
  mkdirSync(join(work, 'cargo')); mkdirSync(home);
  const stableDownload = exactDirectory(downloadHome), stableCargo = exactDirectory(join(work, 'cargo')), stableHome = exactDirectory(home);
  const environment = { ...input, CARGO_HOME: downloadHome, CARGO_NET_OFFLINE: 'false', CARGO_NET_RETRY: '0', RUSTC_BOOTSTRAP: '1',
    CARGO_REGISTRIES_CRATES_IO_INDEX: 'sparse+https://index.crates.io/', CARGO_REGISTRIES_CRATES_IO_PROTOCOL: 'sparse' };
  writeFileSync(join(downloadHome, 'config.toml'), '[net]\nretry = 0\n\n[source.crates-io]\nregistry = "sparse+https://index.crates.io/"\n', { flag: 'wx' });
  execute(input.CARGO, ['vendor', '--locked', '--versioned-dirs', '--manifest-path', join(root, 'Cargo.toml'),
    '--sync', join(library, 'Cargo.toml'), packages], root, environment);
  stableRoot(); stableWork(); stableLibrary(); stableDownload(); stableCargo(); stableHome();
  if (!exactFile(sdkLock).equals(sdkBytes) || !exactFile(stdLock).equals(stdBytes)) throw new Error('SDK准备期间原锁变化');
  if ([...union.values()].some(value => value.source)) {
    // vendor仅承担registry目录源；Git原件仍以原锁固定提交交给Cargo，禁止改成path依赖。
    verifyGitCache(root, downloadHome, union, environment, { execute });
    cpSync(join(downloadHome, 'git'), join(home, 'git'), { recursive: true, force: false, errorOnExist: true });
    for (const [coordinate, value] of union) if (value.source) {
      exactDirectory(join(packages, coordinate));
      rmSync(join(packages, coordinate), { recursive: true });
    }
  }
  verifyVendor(packages, downloadHome, union);
  writeFileSync(join(home, 'config.toml'), offlineConfig(packages), { flag: 'wx' });
  verifyGitCache(root, home, union, input, { execute });
  stableRoot(); stableWork(); stableLibrary(); stableCargo(); stableHome();
  if (!exactFile(sdkLock).equals(sdkBytes) || !exactFile(stdLock).equals(stdBytes)) throw new Error('SDK离线配置交付期间原锁变化');
  return { ...input, CARGO_HOME: home };
}

export function hostChecks(paths) {
  if (!paths.includes('substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs')) return [];
  return [['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface-test', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--doc']];
}
export function gateRange(base, head) {
  if (!shaPattern.test(base ?? '') || !shaPattern.test(head ?? '') || base === head) throw new Error('SDK门禁提交区间无效');
  return { base, head };
}
// 远端覆盖合同初始提交后的全部自有改动，失败后的工具补修不能漏验金额边界。
export function remoteRange(contract, event) {
  gateContract(contract); gateRange(event.before, event.after);
  return gateRange(contract.initial_sha, event.after);
}
export function gateContract(value) {
  if (!value||Object.keys(value).sort().join(',')!==['schema','repository','github_repository','node_tests','checks','upstream','upstream_base','initial_sha','functional_targets','workflows'].sort().join(',')||value.github_repository!=='crcfrcn/polkadot-sdk'||!Array.isArray(value.node_tests)||value.node_tests.join(',')!=='.github/tatagate/test.mjs,.github/workflows/release-sdk.mjs'||value?.schema !== 1 || value.repository !== 'polkadot-sdk' || value.upstream !== 'paritytech/polkadot-sdk'
    || !shaPattern.test(value.upstream_base ?? '') || !shaPattern.test(value.initial_sha ?? '')
    || !Array.isArray(value.functional_targets)||value.functional_targets.join(',')!=='affected-crates-all-targets,affected-crates-doc,workspace-on-lock-or-manifest-change,applicable-wasm-hosts'
    || !Array.isArray(value.checks) || value.checks.join(',') !== 'identity,history,source,workflow,tests,changed-crates') {
    throw new Error('SDK门禁合同无效');
  }
  return value;
}
export function gatePath(value) {
  if (!value || value.startsWith('/') || value.includes('\\') || value.split('/').some(part => ['', '.', '..'].includes(part))) {
    throw new Error('SDK门禁路径越界');
  }
  return value;
}
function command(file, args, root, environment = process.env) {
  if (!file || !file.startsWith('/') || realpathSync(file) !== file
    || !lstatSync(file).isFile() || !(lstatSync(file).mode & 0o111)) throw new Error('SDK门禁缺少准确工具路径');
  const result = spawnSync(file, args, { cwd: root, env: environment, encoding: 'utf8', timeout: 3_600_000,
    // SDK完整metadata当前约13MiB，保留有界缓冲以容纳完整依赖图。
    stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024 });
  if (result.status !== 0 || result.error) {
    process.stderr.write((result.stderr ?? '').slice(-64 * 1024));
    throw new Error('SDK门禁工具检查失败：' + args.slice(0, 4).join(' ') + '；退出码 ' + result.status
      + (result.error ? '；' + result.error.message : ''));
  }
  return result.stdout.trim();
}

// 门禁只使用调用方已准备的离线目录源；完整夹具和Runtime构建不能跳过。
export function gateEnvironment(root, work, input, { canonical = realpathSync, stat = lstatSync, execute = command } = {}) {
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER',
    'RUSTUP_TOOLCHAIN', 'WASM_BUILD_TOOLCHAIN', 'PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN']) {
    if (Object.hasOwn(input, key)) throw new Error('SDK完整门禁拒绝跳过或替换工具：' + key);
  }
  const regular = path => typeof path === 'string' && path.startsWith('/') && resolve(path) === path
    && canonical(path) === path && stat(path).isFile() && !!(stat(path).mode & 0o111);
  const cargo = input.TATAGATE_CARGO, rustc = input.TATAGATE_RUSTC;
  if (!regular(cargo) || !regular(rustc) || dirname(cargo) !== dirname(rustc)
    || input.RUSTC !== rustc || input.CARGO !== cargo
    || execute(rustc, ['--version'], root, input).split(' ')[1] !== '1.97.1'
    || execute(cargo, ['--version'], root, input).split(' ')[1] !== '1.97.1') throw new Error('SDK门禁Rust对象或版本不符');
  if (!work || !work.startsWith('/') || resolve(work) !== work || work === root || !work.startsWith(resolve(root,'target/test') + '/')
    || canonical(work) !== work || !stat(work).isDirectory()) throw new Error('SDK检查中间物目录无效');
  const home = input.CARGO_HOME;
  const boundary = work;
  if (typeof home !== 'string' || !home.startsWith(boundary + '/') || !home.startsWith(work + '/')
    || canonical(home) !== home || !stat(home).isDirectory()) throw new Error('SDK门禁缺少独立离线Cargo主目录');
  const config = join(home, 'config.toml');
  if (canonical(config) !== config || !stat(config).isFile()) throw new Error('SDK门禁离线配置不是准确文件');
  const text = readFileSync(config, 'utf8');
  const directory = text.match(/^directory = (".*")$/mu)?.[1];
  const packages = directory && JSON.parse(directory);
  if (!/^\[net\]\noffline = true\n\n\[source\.crates-io\]\nreplace-with = "verified"\n\n\[source\.verified\]\ndirectory = "[^\n]+"\n$/u.test(text)
    || typeof packages !== 'string' || !packages.startsWith(boundary + '/') || !packages.startsWith(work + '/')
    || canonical(packages) !== packages || !stat(packages).isDirectory()) throw new Error('SDK门禁缺少完整离线目录源');
  return { ...input, RUSTC: rustc, CARGO: cargo, CARGO_NET_OFFLINE: 'true',
    CARGO_TARGET_DIR: join(work, 'cargo-target'), RUSTC_BOOTSTRAP: '1', WASM_BUILD_STD: '1',
    // OUT_DIR位于独立临时目录，WASM子工程必须明确继承受检源码的原锁。
    WASM_BUILD_WORKSPACE_HINT: root };
}
function git(root, args) {
  const tool = process.env.PRODUCT_GIT_BIN;
  if (!tool || realpathSync(tool) !== tool || !lstatSync(tool).isFile()) throw new Error('SDK门禁缺少准确Git');
  if (command(tool, ['--version'], root) !== 'git version 2.54.0') throw new Error('SDK门禁Git版本不符');
  return execFileSync(tool, ['-C', root, ...args], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024,
    env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' }, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}
export function identity(root, physical = false) {
  if (realpathSync(root) !== root || !lstatSync(root + '/.git').isDirectory()
    || git(root, ['rev-parse', '--show-toplevel']) !== root
    || lstatSync(root+'/.git').isSymbolicLink()
    || git(root,['rev-parse','--is-bare-repository'])!=='false'
    || resolve(root,git(root,['rev-parse','--git-common-dir']))!==join(root,'.git')
    || git(root,['rev-parse','--absolute-git-dir'])!==join(root,'.git')
    || !['https://github.com/crcfrcn/polkadot-sdk','https://github.com/crcfrcn/polkadot-sdk.git'].includes(git(root, ['remote', 'get-url','--all', 'origin']))) throw new Error('SDK门禁仓库身份无效');
  if(process.env.GITHUB_ACTIONS!=='true'&&git(root,['symbolic-ref','--quiet','--short','HEAD'])!=='main')throw Error('SDK本机门禁只接受所属main');
  if (physical && (root !== '/Users/rhett/polkadot-sdk' || git(root, ['branch', '--show-current']) !== 'main'
    || git(root, ['remote', 'get-url', 'upstream']) !== 'https://github.com/paritytech/polkadot-sdk.git')) throw new Error('SDK正式开发入口无效');
}
function checkedSource(root, path) {
  const absolute = resolve(root, gatePath(path));
  if (!absolute.startsWith(root + '/') || realpathSync(absolute) !== absolute || !lstatSync(absolute).isFile()) throw new Error('SDK源码不是准确文件');
  const text = readFileSync(absolute, 'utf8');
  if (/-----BEGIN [A-Z ]*PRIVATE KEY-----|github_pat_[A-Za-z0-9_]{20,}|ghs_[A-Za-z0-9_]{20,}/u.test(text)
    || /\/Users\/[A-Za-z0-9_-]+\/(?:tataconsole|GMB|TATA|TUYU)\//u.test(text)) throw new Error('SDK源码包含机密或私有工作区路径');
}
// 词法扫描保留真实代码与注释位置；字符串、正则及模板正文不作为实现注释。
export function lexicalParts(path, source) {
  const extension=extname(path).toLowerCase(), javascript=['.js','.jsx','.mjs','.ts','.tsx'].includes(extension);
  const comments=[], code=source.split('');let index=0;
  const blank=(begin,end)=>{for(let at=begin;at<end;at++)if(source[at]!=='\n'&&source[at]!=='\r')code[at]=' ';};
  const quote=(delimiter,triple=false,interpolated=false)=>{
    const size=triple?3:1;blank(index,index+size);index+=size;
    while(index<source.length){
      if(source[index]==='\\'){blank(index,index+2);index+=2;continue;}
      if(interpolated&&source.startsWith('${',index)){blank(index,index+2);index+=2;scan(true);continue;}
      if(source.startsWith(delimiter.repeat(size),index)){blank(index,index+size);index+=size;return;}
      blank(index,index+1);index++;
    }
  };
  const scan=(interpolation=false)=>{
    let previous='',word='',depth=1;
    while(index<source.length){
      const value=source[index];
      if(/\s/u.test(value)){index++;continue;}
      if(interpolation&&value==='}'){if(--depth===0){blank(index,index+1);index++;return;}index++;previous='}';continue;}
      if(interpolation&&value==='{')depth++;
      const lineComment=(['.py','.sh'].includes(extension)&&value==='#'&&!source.startsWith('#!',index))
        ||extension==='.sql'&&source.startsWith('--',index)
        ||!['.py','.sh','.sql'].includes(extension)&&source.startsWith('//',index);
      if(lineComment){const begin=index,end=source.indexOf('\n',index);index=end<0?source.length:end;comments.push(source.slice(begin,index));blank(begin,index);continue;}
      if(!['.py','.sh'].includes(extension)&&source.startsWith('/*',index)){
        const begin=index;let nested=1;index+=2;
        while(index<source.length&&nested){if(extension==='.rs'&&source.startsWith('/*',index)){nested++;index+=2;}else if(source.startsWith('*/',index)){nested--;index+=2;}else index++;}
        comments.push(source.slice(begin,index));blank(begin,index);continue;
      }
      if(extension==='.rs'){
        const raw=/^(?:b)?r(#+)?"/u.exec(source.slice(index));
        if(raw){const begin=index,close='"'+(raw[1]||''),end=source.indexOf(close,index+raw[0].length);index=end<0?source.length:end+close.length;blank(begin,index);previous='literal';continue;}
        if(value==="'"&&!/^'(?:\\(?:u\{[0-9a-fA-F]+\}|x[0-9a-fA-F]{2}|.)|[^'\\\n])'/u.test(source.slice(index))){index++;previous=value;continue;}
      }
      if(value==='"'||value==="'"||value==='`'){
        quote(value,['.dart','.py'].includes(extension)&&source.startsWith(value.repeat(3),index),javascript&&value==='`'||extension==='.dart'&&source[index-1]!=='r');previous='literal';word='';continue;
      }
      if(javascript&&value==='/'&&(!previous||/[=(:,!\[{};?]/u.test(previous)||['return','throw','yield','case'].includes(word))){
        const begin=index++;let bracket=false;
        while(index<source.length){const current=source[index++];if(current==='\\'){index++;continue;}if(current==='[')bracket=true;else if(current===']')bracket=false;else if(current==='/'&&!bracket)break;else if(current==='\n')break;}
        while(/[a-z]/iu.test(source[index]||''))index++;blank(begin,index);previous='literal';word='';continue;
      }
      if(/[A-Za-z_$]/u.test(value)){const begin=index++;while(/[A-Za-z0-9_$]/u.test(source[index]||''))index++;word=source.slice(begin,index);previous='word';continue;}
      previous=value;word='';index++;
    }
  };
  scan();return {comments:comments.join('\n'),code:code.join('')};
}

export function commentText(path, source) { return lexicalParts(path,source).comments; }


function temporaryComments(path, source) {
  return commentText(path, source).split('\n').filter((line) => /(?:TODO|FIXME|HACK|XXX)\b/u.test(line));
}

// 上游说明只能逐字、按原有数量保留；复制同一句到新位置不能增加允许数量。

export function hasFirstPartyTemporaryComments(path, source, upstream = '') {
  const retained = new Map();
  for (const comment of temporaryComments(path, upstream)) retained.set(comment, (retained.get(comment) ?? 0) + 1);
  return temporaryComments(path, source).some((comment) => {
    const count = retained.get(comment) ?? 0;
    if (count === 0) return true;
    retained.set(comment, count - 1);
    return false;
  });
}


export function validateOwnedDocuments(root){
 const path=join(root,'PolkadotSDK.md'),info=lstatSync(path,{throwIfNoEntry:false});
 if(!info||!info.isFile()||info.isSymbolicLink()||!info.size||realpathSync(path)!==path)throw Error('SDK唯一自有技术文档无效');
 // README与官方上游资料保留原件，不把它们列为自有技术文档或开发凭证。
 for(const entry of readdirSync(root)){if(entry!=='PolkadotSDK.md'&&entry!=='README.md'&&/\.md$/iu.test(entry)){
  const listed=git(root,['ls-tree','--name-only',JSON.parse(readFileSync(join(root,'.github/tatagate/contracts.json'),'utf8')).upstream_base,'--',entry]);
  if(listed!==entry)throw Error('SDK新增额外根技术文档');
 }}
}
export function validateOwnedNodeTests(root,registered,upstream){
 const tracked=git(root,['ls-files','-z']).split('\0').filter(Boolean);
 const upstreamTests=new Set(git(root,['ls-tree','-r','--name-only','-z',upstream]).split('\0').filter(Boolean));
 const actual=tracked.filter(path=>/(?:^|\/)(?:test\.mjs|[^/]+[._-](?:test|spec)\.mjs)$/u.test(path)&&!upstreamTests.has(path)).sort();
 if(actual.join('\0')!==[...registered].sort().join('\0')||new Set(registered).size!==registered.length||!actual.length)throw Error('SDK自有Node测试清单不闭合');
 for(const path of actual){const file=join(root,gatePath(path)),info=lstatSync(file);if(!info.isFile()||info.isSymbolicLink()||!info.size||realpathSync(file)!==file)throw Error('SDK真实测试入口无效');}
}
// 逐文件与最终汇总必须对应同一非空清单，拒绝漏文件、重复汇总及伪造总数。
export default async function* reporter(events) {
  async function* checked() {
    let list;
    try{list=JSON.parse(process.env.TATAGATE_NODE_TESTS||'null');}catch{list=null;}
    const validList=Array.isArray(list)&&list.length>0&&list.every(file=>typeof file==='string'&&isAbsolute(file)&&resolve(file)===file)&&new Set(list).size===list.length;
    const expected=new Set(validList?list:[]),seen=new Set();let cumulative=false,total=0,invalid=!validList;
    for await(const event of events){
      if(event.type==='test:summary'){
        const data=event.data;let valid=successfulTestSummary(data);
        if(data?.file!==undefined){
          if(typeof data.file!=='string'||!data.file)valid=false;
          else{const file=resolve(data.file);if(!expected.has(file)||seen.has(file)||cumulative)valid=false;seen.add(file);total+=data.counts?.tests||0;}
        }else{if(cumulative||seen.size!==expected.size||[...expected].some(file=>!seen.has(file))||data?.counts?.tests!==total)valid=false;cumulative=true;}
        if(!valid)invalid=true;
      }
      yield event;
    }
    if(invalid||!cumulative||seen.size!==expected.size){process.exitCode=1;yield{type:'test:diagnostic',data:{nesting:0,message:'产品门禁缺少逐文件完整成功回执。'}};}
  }
  yield* Readable.from(checked()).pipe(spec());
}

// 汇总必须非空且没有失败、取消、待办或跳过，不能用零用例退出码冒充验收。
export function successfulTestSummary(data) {
  const counts = data?.counts;
  return data?.success === true && counts && Number.isSafeInteger(counts.tests) && counts.tests > 0
    && ['failed', 'skipped', 'todo', 'cancelled'].every(name => counts[name] === 0)
    && Number.isSafeInteger(counts.passed) && counts.passed === counts.tests;
}



export function runGate(root, baseSHA, headSHA, work) {
  root = resolve(root); identity(root); const range = gateRange(baseSHA, headSHA);
  const contract = gateContract(JSON.parse(readFileSync(join(root, '.github/tatagate/contracts.json'), 'utf8')));
  if (git(root, ['rev-parse', 'HEAD']) !== range.head || git(root, ['status', '--porcelain=v1', '--untracked-files=all']) !== '') throw new Error('SDK门禁快照不一致');
  git(root, ['merge-base', '--is-ancestor', range.base, range.head]);
  git(root, ['merge-base', '--is-ancestor', contract.initial_sha, range.head]);
  git(root, ['merge-base', '--is-ancestor', contract.upstream_base, contract.initial_sha]);
  git(root, ['diff', '--check', range.base, range.head]);
  const paths = git(root, ['diff', '--name-only', '-z', range.base, range.head]).split('\u0000').filter(Boolean);
  const implementation=paths.filter(path=>/\.(?:rs|mjs|js|ts|py|sh|toml)$/u.test(path)&&!/(?:^|\/)(?:test|tests)\//u.test(path)&&!/(?:^|[/._-])test\.mjs$/u.test(path));
  if(implementation.length){const meaningful=path=>{if(!existsSync(join(root,path)))return false;const old=git(root,['ls-tree','--name-only',range.base,'--',path])?git(root,['show',range.base+':'+path]):'';return old.replace(/\s/gu,'')!==readFileSync(join(root,path),'utf8').replace(/\s/gu,'');};if(!paths.includes('PolkadotSDK.md')||!meaningful('PolkadotSDK.md')||!paths.some(path=>/(?:^|[/._-])test\.mjs$|(?:^|\/)tests?\//u.test(path)&&meaningful(path)))throw Error('SDK自有实现缺少所属资料或真实回归同步');}
  const crates = new Set();
  for (const path of paths) {
    gatePath(path);
    const absolute = join(root, path);
    if (!existsSync(absolute)) continue;
    checkedSource(root,path);
    if(/\.(?:rs|mjs|js|ts|py|sh|c|h|cpp|swift)$/u.test(path)){
      const upstreamPaths=git(root,['ls-tree','--name-only',contract.upstream_base,'--',path]);
      const original=upstreamPaths?git(root,['show',contract.upstream_base+':'+path]):'';
      if(hasFirstPartyTemporaryComments(path,readFileSync(absolute,'utf8'),original))throw Error('SDK自有新增临时注释：'+path);
    }
    if (path.startsWith('.github/workflows/') && /\.ya?ml$/u.test(path)) {
      command(process.env.TATAGATE_ACTIONLINT, ['-shellcheck=', '-pyflakes=', '-ignore', '^unexpected key "queue" for "concurrency" section[.]', '-ignore', '^label "xcode-27" is unknown[.]', path], root);
    }
    if (path.endsWith('.rs') || path.endsWith('Cargo.toml')) {
      let directory = dirname(absolute);
      while (directory !== root && directory.startsWith(root + '/')) {
        const manifest = join(directory, 'Cargo.toml');
        if (existsSync(manifest)) {
          const source = readFileSync(manifest, 'utf8');
          const packageBlock = source.match(/\[package\]([\s\S]*?)(?=\n\[|$)/u)?.[1];
          const name = packageBlock?.match(/^name\s*=\s*"([a-z0-9-]+)"/mu)?.[1];
          if (name) { crates.add(name); break; }
        }
        directory = dirname(directory);
      }
    }
  }
  validateOwnedDocuments(root);
  validateOwnedNodeTests(root,contract.node_tests,contract.upstream_base);
  if(process.version!=='v25.2.1')throw Error('SDK门禁Node版本不符');
  command(process.execPath,['--test','--test-reporter='+join(root,'.github/tatagate/index.mjs'),...contract.node_tests],root,{...process.env,TATAGATE_NODE_TESTS:JSON.stringify(contract.node_tests.map(path=>join(root,path)))});
  const functionalResults=[],hosts = hostChecks(paths);
  if (crates.size || hosts.length || paths.includes('Cargo.lock') || paths.includes('Cargo.toml')) {
    const environment = gateEnvironment(root, work, process.env), cargo = environment.CARGO;
    const metadata = JSON.parse(command(cargo, ['metadata', '--locked', '--offline', '--format-version', '1'], root, environment));
    verifyGitCache(root, environment.CARGO_HOME, lockedPackages(readFileSync(join(root, 'Cargo.lock'), 'utf8')), environment, { metadata });
    for (const name of crates) {
      command(cargo, ['check', '--locked', '--offline', '-p', name], root, environment);
      const output=command(cargo, ['test', '--locked', '--offline', '-p', name, '--all-targets','--','--color','never'], root, environment);
      const item=sdkFunctionalResult(output,{target:name,documentation:false});functionalResults.push(item);
      functionalResults.push(sdkFunctionalResult(command(cargo, ['test', '--locked', '--offline', '-p', name, '--doc','--','--color','never'], root, environment),{target:name,documentation:true}));
    }
    for(const args of hosts){functionalResults.push(sdkFunctionalResult(command(cargo,[...args,'--','--color','never'],root,environment),{target:args.join(' '),documentation:args.includes('--doc')}));}
    // workspace声明与锁整体改动需要全工作空间检查，不能只验证门禁自身。
    if(paths.includes('Cargo.lock')||paths.includes('Cargo.toml')){
      command(cargo,['check','--locked','--offline','--workspace','--all-targets'],root,environment);
      functionalResults.push(sdkFunctionalResult(command(cargo,['test','--locked','--offline','--workspace','--all-targets','--','--color','never'],root,environment),{target:'workspace',documentation:false}));
      functionalResults.push(sdkFunctionalResult(command(cargo,['test','--locked','--offline','--workspace','--doc','--','--color','never'],root,environment),{target:'workspace',documentation:true}));
    }
  }
  if(git(root,['rev-parse','HEAD'])!==range.head||git(root,['status','--porcelain=v1','--untracked-files=all'])!=='')throw Error('SDK门禁执行改变受检快照');
  return { repository: 'polkadot-sdk', base_sha: range.base, head_sha: range.head, changed_crates: [...crates].sort(), functional_results:functionalResults };
}
if (!['github','cleanup'].includes(process.argv[2]) && process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const [mode, ...args] = process.argv.slice(2);
    if (mode === 'physical' && args.length === 1) identity(resolve(args[0]), true);
    else if(mode==='local'&&args.length===4){const [root,base,head,requested]=args;exactDirectory(requested);if(readdirSync(requested).length||root===requested||root.startsWith(requested+'/'))throw Error('SDK请求协调目录无效');const parent=join(root,'target/test');mkdirSync(parent,{recursive:true});exactDirectory(parent);const work=join(parent,'tatagate-local-'+process.pid+'-'+Date.now());mkdirSync(work,{mode:0o700});try{const rustc=process.env.TATAGATE_RUSTC,cargo=process.env.TATAGATE_CARGO;if(!rustc||!cargo||dirname(rustc)!==dirname(cargo))throw Error('SDK本机缺少同版准确Rust对象');const library=join(command(rustc,['--print','sysroot'],root),'lib/rustlib/src/rust/library');const input={...process.env,RUSTC:rustc,CARGO:cargo};const prepared=prepareOffline(root,work,input,library);Object.assign(process.env,prepared);console.log(JSON.stringify(runGate(root,base,head,work)));}finally{rmSync(work,{recursive:true,force:true});}}
    else if (['prepare', 'remote'].includes(mode) && args.length === 0) {
      const root = realpathSync(process.cwd()), work = process.env.TATAGATE_WORK;
      const event = remoteContext(root, work, process.env);
      identity(root);
      if (git(root, ['rev-parse', 'HEAD']) !== event.after || git(root, ['status', '--porcelain=v1', '--untracked-files=all']) !== '') throw new Error('SDK远端准备源码提交不符');
      const library = remoteTools(root, work, process.env);
      if (process.execPath !== process.env.TATAGATE_NODE) throw new Error('SDK远端Node执行对象不符');
      if (mode === 'prepare') {
        const environment = prepareOffline(root, work, process.env, library);
        gateEnvironment(root, work, environment);
        console.log(JSON.stringify({ repository: 'polkadot-sdk', head_sha: event.after, packages: 1556, cargo_home: environment.CARGO_HOME }));
      } else {
        if (process.env.CARGO_HOME !== join(work, 'cargo/home')) throw new Error('SDK远端离线主目录不符');
        const sdkLock = exactFile(join(root, 'Cargo.lock')), stdLock = exactFile(join(library, 'Cargo.lock'));
        if (digest(sdkLock) !== 'e87457b0d643498e75840b68b2a4a33d26ae316cc43514eae3f34f63e4fc0780'
          || digest(stdLock) !== '02120dd57c4c5fd70c81fd92472681c8de5cc2dd78258276da37bb2253666061') throw new Error('SDK远端原锁不在获准闭包');
        const union = lockedUnion(sdkLock.toString('utf8'), stdLock.toString('utf8'));
        if (union.size !== 1556) throw new Error('SDK远端联合闭包数量不符');
        verifyVendor(join(work, 'cargo/packages'), join(work, 'cargo-download/home'), union);
        verifyGitCache(root, process.env.CARGO_HOME, union, process.env);
        const range = remoteRange(JSON.parse(readFileSync(join(root, '.github/tatagate/contracts.json'), 'utf8')), event);
        console.log(JSON.stringify(runGate(root, range.base, range.head, work)));
      }
    } else throw new Error('SDK门禁参数无效');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}

// SDK按受影响包绑定真实libtest摘要；文档零用例是编译结果，不冒充业务测试成功。
export function sdkFunctionalResult(source,{target,documentation=false}){
 if(typeof source!=='string'||typeof target!=='string'||!target||/test result: FAILED|\bFAILED\b/u.test(source))throw Error('SDK真实功能测试失败');
 const rows=[...source.matchAll(/^test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored; (\d+) measured; (\d+) filtered out;/gmu)];
 if(!rows.length||rows.some(row=>Number(row[2])||Number(row[3])||Number(row[5])))throw Error('SDK功能测试摘要缺失、跳过或过滤');
 const tests=rows.reduce((count,row)=>count+Number(row[1]),0);
 if(!documentation&&!tests)throw Error('SDK受影响包功能测试为空');
 return {target,type:documentation?'documentation':'all-targets',tests,status:'success'};
}

// GitHub入口和清理只处理本仓tatagate.yml；产品检查仍由本仓原有实现执行。
export function tataGateBranch(repositoryRoot) {
  if (process.env.GITHUB_ACTIONS === 'true') { tataGateContext(repositoryRoot); return true; }
  return tataGateExec(process.env.PRODUCT_GIT_BIN || '/usr/bin/git', ['-C',repositoryRoot,'branch','--show-current'], {encoding:'utf8'}).trim() === 'main';
}
export function tataGateContext(repositoryRoot, input=process.env, event=JSON.parse(tataGateRead(input.GITHUB_EVENT_PATH,'utf8'))) {
  if (input.GITHUB_ACTIONS !== 'true' || input.GITHUB_EVENT_NAME !== 'push'
    || input.GITHUB_REPOSITORY !== tataGateOwner || input.GITHUB_REF !== 'refs/heads/main'
    || input.GITHUB_WORKSPACE !== repositoryRoot || tataGateReal(repositoryRoot) !== repositoryRoot
    || event.repository?.full_name !== tataGateOwner || event.ref !== input.GITHUB_REF
    || event.deleted === true || event.after !== input.GITHUB_SHA
    || !/^[a-f0-9]{40}$/u.test(event.after || '') || !/^[a-f0-9]{40}$/u.test(event.before || '')
    || event.before === event.after || input.GITHUB_WORKFLOW_REF!==tataGateOwner+'/.github/workflows/tatagate.yml@refs/heads/main') {
    throw Error('本仓塔塔门禁GitHub事件身份无效');
  }
  const git=input.PRODUCT_GIT_BIN || '/usr/bin/git';
  const read=args=>tataGateExec(git,['-c','core.hooksPath=/dev/null','-C',repositoryRoot,...args],{encoding:'utf8'}).trim();
  if (read(['rev-parse','HEAD']) !== event.after || read(['rev-parse','--show-toplevel']) !== repositoryRoot
    || !['https://github.com/'+tataGateOwner,'https://github.com/'+tataGateOwner+'.git'].includes(read(['remote','get-url','--all','origin']))) {
    throw Error('本仓塔塔门禁GitHub提交或来源无效');
  }
  if(read(['status','--porcelain=v1','--untracked-files=all']))throw Error('本仓塔塔门禁GitHub检出存在未提交改动');
  if(input.GITHUB_JOB==='gate'&&event.before!=='0'.repeat(40)){
    try{tataGateExec(git,['-C',repositoryRoot,'merge-base','--is-ancestor',event.before,event.after],{encoding:'utf8',stdio:'pipe'});}catch{throw Error('本仓塔塔门禁GitHub提交范围不是快进祖先');}
  }
  return {...event,before:event.before === '0'.repeat(40) ? '4b825dc642cb6eb9a060e54bf8d69288fbee4904' : event.before};
}
export function tataGateValidateWorkflow(source) {
  const jobs=source?.slice(source.indexOf('\njobs:\n')).match(/^  [a-z][a-z0-9_]*:$/gmu);
  const entry=new URL(import.meta.url).pathname.split('/').at(-1);
  const gate=source?.split('  gate:\n')[1]?.split('\n  cleanup:')[0];
  if(!gate||/^    continue-on-error:/mu.test(gate)||!source.includes('permissions:\n  contents: read\n'))throw Error('本仓塔塔门禁检查权限或结果处理无效');
  if(JSON.stringify(jobs)!==JSON.stringify(['  gate:','  cleanup:'])||!source.includes('run: node .github/tatagate/'+entry+' github\n')||!source.includes('run: node .github/tatagate/'+entry+' cleanup\n'))throw Error('本仓塔塔门禁Job或执行入口无效');
  if (typeof source !== 'string' || !source.startsWith('name: '+tataGateOwner.split('/')[1]+'.tatagate\n')
    || !/^  push:\n    branches: \[main\]$/mu.test(source)
    || /^\s*(?:workflow_run|workflow_dispatch|schedule|pull_request):/mu.test(source)
    || !source.includes('group: "${{ github.repository }}-tatagate"')
    || !/^  cancel-in-progress: false$/mu.test(source) || !/^  queue: max$/mu.test(source)
    || !/^  gate:$/mu.test(source) || !/^  cleanup:$/mu.test(source)
    || !/^    needs: \[gate\]$/mu.test(source) || !source.includes('if: ${{ always() }}')
    || !/^    continue-on-error: true$/mu.test(source)
    || !source.includes('TATAGATE_RESULT: "${{ needs.gate.result }}"')
    || !source.includes('persist-credentials: false')
    || !source.includes(' github\n') || !source.includes(' cleanup\n')) throw Error('本仓塔塔门禁Workflow合同无效');
  return true;
}
function tataGateWorkflowRun(run) {
  return Number.isSafeInteger(run?.id) && run.id>0 && Number.isSafeInteger(run.run_number) && run.run_number>0
    && Number.isSafeInteger(run.run_attempt) && run.run_attempt>0
    && run.path === '.github/workflows/tatagate.yml' && run.event === 'push' && run.head_branch === 'main'
    && run.repository?.full_name === tataGateOwner && /^[a-f0-9]{40}$/u.test(run.head_sha || '')
    && Number.isFinite(Date.parse(run.created_at));
}
export function tataGateCleanupPlan(rows,current,result) {
  if (!['success','failed'].includes(result) || !tataGateWorkflowRun(current) || !Array.isArray(rows)) throw Error('本仓塔塔门禁清理身份无效');
  return rows.filter(run=>tataGateWorkflowRun(run) && run.status==='completed' && typeof run.conclusion==='string'
    && run.id!==current.id && run.run_number<current.run_number
    && (run.conclusion==='success'?'success':'failed')===result).sort((a,b)=>a.run_number-b.run_number);
}
async function tataGateAPI(path,{method='GET',fetchImpl=fetch,token=process.env.GH_TOKEN}={}) {
  if (typeof token!=='string' || !token || typeof path!=='string' || path.includes('..') || path.startsWith('/') || /[\r\n]/u.test(path)) throw Error('本仓塔塔门禁API参数无效');
  let response;
  try {response=await fetchImpl('https://api.github.com/repos/'+tataGateOwner+'/'+path,{method,redirect:'error',
    headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'TataGate'},
    signal:AbortSignal.timeout(30000)});}catch{throw Error('本仓塔塔门禁API连接未确认');}
  if(response.status===404 && method==='GET')return null;
  if(!response.ok)throw Error('本仓塔塔门禁API失败：HTTP '+response.status);
  if(response.status===204)return null;
  let size=0;const parts=[];
  if(!response.body)throw Error('本仓塔塔门禁API回执缺失');
  for await(const chunk of response.body){size+=chunk.length;if(size>8*1024**2)throw Error('本仓塔塔门禁API回执超限');parts.push(chunk);}
  try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(parts)));}catch{throw Error('本仓塔塔门禁API回执无效');}
}
async function tataGateHistory(current,api) {
  const read=async(start,end)=>{
    const query='actions/workflows/tatagate.yml/runs?event=push&branch=main&status=completed&created='+encodeURIComponent(new Date(start).toISOString().slice(0,19)+'Z..'+new Date(end).toISOString().slice(0,19)+'Z');
    const first=await api(query+'&per_page=100&page=1');
    if(!Number.isSafeInteger(first?.total_count)||!Array.isArray(first.workflow_runs))throw Error('本仓塔塔门禁历史清单无效');
    if(first.total_count>1000){const middle=Math.floor((start+end)/2000)*1000;if(middle<=start||middle>=end)throw Error('本仓塔塔门禁历史超过同秒上限');return [...await read(start,middle),...await read(middle+1000,end)];}
    const rows=[...first.workflow_runs];
    for(let page=2;rows.length<first.total_count;page++){const value=await api(query+'&per_page=100&page='+page);if(!Array.isArray(value?.workflow_runs)||!value.workflow_runs.length)throw Error('本仓塔塔门禁历史分页不完整');rows.push(...value.workflow_runs);}
    return rows;
  };
  const rows=await read(Date.UTC(2008,0,1),Math.floor(Date.parse(current.created_at)/1000)*1000);
  return [...new Map(rows.map(run=>[run.id,run])).values()];
}
export async function tataGateCleanup(result,identity,api=tataGateAPI) {
  const current=await api('actions/runs/'+identity.id);
  if(identity.attempt!==undefined&&current?.run_attempt!==identity.attempt)throw Error('本仓塔塔门禁当前Attempt不符');
  if(!tataGateWorkflowRun(current)||current.id!==identity.id||current.head_sha!==identity.sha)throw Error('本仓塔塔门禁当前Run回读无效');
  const plan=tataGateCleanupPlan(await tataGateHistory(current,api),current,result),removed=[];
  for(const candidate of plan){
    const path='actions/runs/'+candidate.id;
    const latest=await api('actions/runs/'+current.id);
    if(!latest||latest.head_sha!==current.head_sha||latest.run_attempt!==current.run_attempt)throw Error('本仓塔塔门禁当前Run已变化');
    const again=await api(path);
    if(again===null){removed.push(candidate.id);continue;}
    if(again.run_attempt!==candidate.run_attempt||again.conclusion!==candidate.conclusion
      ||tataGateCleanupPlan([again],current,result).length!==1)throw Error('本仓塔塔门禁旧Run已变化，停止清理');
    try{await api(path,{method:'DELETE'});}catch(error){if(await api(path)!==null)throw error;}
    if(await api(path)!==null)throw Error('本仓塔塔门禁旧Run删除回查失败');
    removed.push(candidate.id);
  }
  return removed;
}
export async function tataGateCommand(mode) {
  const {fileURLToPath}=await import('node:url'),{resolve}=await import('node:path');
  const repositoryRoot=resolve(fileURLToPath(new URL('../..',import.meta.url)));
  const event=tataGateContext(repositoryRoot);
  tataGateValidateWorkflow(tataGateRead(repositoryRoot+'/.github/workflows/tatagate.yml','utf8'));
  if(mode==='github'){if(process.env.GITHUB_JOB!=='gate')throw Error('本仓塔塔门禁Job身份无效');const receipt=await tataGateRunOwn(repositoryRoot,event);console.log(JSON.stringify({repository:tataGateOwner,source_sha:event.after,receipt}));return receipt;}
  if(process.env.GITHUB_JOB!=='cleanup')throw Error('本仓塔塔门禁清理Job身份无效');
  const result=process.env.TATAGATE_RESULT;
  if(!['success','failure','cancelled','skipped'].includes(result))throw Error('本仓塔塔门禁前置结果无效');
  const id=Number(process.env.GITHUB_RUN_ID);
  if(!Number.isSafeInteger(id)||id<=0)throw Error('本仓塔塔门禁Run编号无效');
  const jobs=await tataGateAPI('actions/runs/'+id+'/jobs?filter=latest&per_page=100');
  const gate=jobs?.jobs?.find(job=>job.name==='gate');
  if(gate?.status!=='completed'||typeof gate.conclusion!=='string'||(gate.conclusion==='success')!==(result==='success'))throw Error('本仓塔塔门禁前置结果与GitHub不一致');
  const removed=await tataGateCleanup(result==='success'?'success':'failed',{id,sha:event.after,attempt:Number(process.env.GITHUB_RUN_ATTEMPT)});
  const summary='塔塔门禁'+(result==='success'?'成功':'失败')+'；同类旧Run已清理：'+(removed.join('、')||'无')+'。\n';
  if(process.env.GITHUB_STEP_SUMMARY){const {appendFileSync}=await import('node:fs');appendFileSync(process.env.GITHUB_STEP_SUMMARY,summary);}
  console.log(summary.trim());
}
if(process.argv[1] && ['github','cleanup'].includes(process.argv[2]) && process.argv.length===3
  && new URL('file:'+process.argv[1]).href===import.meta.url){
  try{await tataGateCommand(process.argv[2]);}catch(error){console.error(error.message?.startsWith('本仓')?error.message:'本仓塔塔门禁执行失败');process.exitCode=1;}
}

export async function tataGatePrepareTools(work) {
  const {createHash}=await import('node:crypto'),{mkdirSync,writeFileSync}=await import('node:fs');
  const {spawnSync}=await import('node:child_process');
  const invoke=(file,args,env=process.env)=>{const result=spawnSync(file,args,{cwd:work,env,stdio:'inherit'});if(result.error||result.signal||result.status!==0)throw Error('本仓SDK门禁工具准备失败');};
  const archive=async(url,sha,path)=>{const response=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(120000)});if(!response.ok)throw Error('本仓SDK门禁工具下载失败');const bytes=Buffer.from(await response.arrayBuffer());if(createHash('sha256').update(bytes).digest('hex')!==sha)throw Error('本仓SDK门禁工具归档摘要不符');writeFileSync(path,bytes,{flag:'wx'});};
  const tools=join(work,'gate-tools');mkdirSync(tools);
  const gitArchive=join(tools,'git.tar.xz');
  await archive('https://www.kernel.org/pub/software/scm/git/git-2.54.0.tar.xz','f689162364c10de79ef89aa8dbf48731eb057e34edbbd20aca510ce0154681a3',gitArchive);
  invoke('/usr/bin/tar',['-xf',gitArchive,'-C',tools]);
  const prefix=join(tools,'git');
  invoke('/usr/bin/make',['-C',join(tools,'git-2.54.0'),'-j2','prefix='+prefix,'NO_GETTEXT=YesPlease','NO_TCLTK=YesPlease','NO_PERL=YesPlease','NO_PYTHON=YesPlease','NO_OPENSSL=YesPlease','all']);
  invoke('/usr/bin/make',['-C',join(tools,'git-2.54.0'),'prefix='+prefix,'NO_GETTEXT=YesPlease','NO_TCLTK=YesPlease','NO_PERL=YesPlease','NO_PYTHON=YesPlease','NO_OPENSSL=YesPlease','install']);
  const lint=join(tools,'actionlint');mkdirSync(lint);
  const lintArchive=join(tools,'actionlint.tar.gz');
  await archive('https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_darwin_arm64.tar.gz','aba9ced2dee8d27fecca3dc7feb1a7f9a52caefa1eb46f3271ea66b6e0e6953f',lintArchive);
  invoke('/usr/bin/tar',['-xf',lintArchive,'-C',lint]);
  return {git:join(prefix,'bin/git'),actionlint:join(lint,'actionlint')};
}
export function tataGateResourceRoots(repositoryRoot) {
  const supply=join(repositoryRoot,'target/test');
  return {supply,work:join(supply,'tatagate')};
}
async function tataGateRunOwn(repositoryRoot,event) {
  if(process.platform!=='darwin'||process.arch!=='arm64')throw Error('本仓SDK门禁要求登记的Apple ARM宿主');
  const {supply:resourceRoot,work}=tataGateResourceRoots(repositoryRoot);mkdirSync(work,{recursive:true});
  const gateTools=await tataGatePrepareTools(work);
  const build=await import('../../scripts/build.mjs');
  const supply=await build.prepareResourceSupply('sdk',resourceRoot,{run_id:String(process.env.GITHUB_RUN_ID)},{offline:false});
  const env=build.resourceEnvironment('sdk',resourceRoot,supply),rustc=env.RUSTC,cargo=join(dirname(rustc),'cargo');
  Object.assign(env,{CARGO:cargo,TATAGATE_CARGO:cargo,TATAGATE_RUSTC:rustc,PRODUCT_GIT_BIN:gateTools.git,
    TATAGATE_ACTIONLINT:gateTools.actionlint,LIBCLANG_PATH:join(env.DEVELOPER_DIR,'Toolchains/XcodeDefault.xctoolchain/usr/lib')});
  Object.assign(process.env,env);
  const library=join(command(rustc,['--print','sysroot'],repositoryRoot,env),'lib/rustlib/src/rust/library');
  Object.assign(process.env,prepareOffline(repositoryRoot,work,process.env,library));
  const range=remoteRange(JSON.parse(tataGateRead(join(repositoryRoot,'.github/tatagate/contracts.json'),'utf8')),event);
  return runGate(repositoryRoot,range.base,range.head,work);
}
