// 正常、失败及边界测试验证同一公开SDK门禁，不依赖私有资料或其它产品。
import assert from 'node:assert/strict';
import test from 'node:test';
import { gateContract, gatePath, gateRange, gateEnvironment, lockedPackages, lockedUnion, remoteContext,
  remoteTools, prepareOffline, verifyVendor, verifyGitCache, lockedGitSource, hostChecks, remoteRange } from './index.mjs';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, realpathSync, rmSync, symlinkSync, renameSync, linkSync, cpSync } from 'node:fs';
import { createHash } from 'node:crypto';
// SDK测试数据同归本产品target；本地和远端不借用系统临时根。
const tmpdir=()=>{const root=new URL('../../target/test/',import.meta.url);mkdirSync(root,{recursive:true});return realpathSync(root);};
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';
const contract = JSON.parse(readFileSync(new URL('./contracts.json', import.meta.url), 'utf8'));
test('准确SDK来源与提交区间有效', () => {
  assert.equal(gateContract(contract).repository, 'polkadot-sdk');
  assert.deepEqual(gateRange('a'.repeat(40), 'b'.repeat(40)), { base: 'a'.repeat(40), head: 'b'.repeat(40) });
  assert.equal(gatePath('substrate/frame/revive/src/lib.rs'), 'substrate/frame/revive/src/lib.rs');
});

const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const header = '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n';
const lock = entries => header + entries.map(([name, version, checksum]) => '[[package]]\nname = ' + JSON.stringify(name)
  + '\nversion = ' + JSON.stringify(version) + '\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = '
  + JSON.stringify(checksum) + '\n\n').join('');
function fixture(context) {
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-remote-preparation-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  const root = join(directory, 'repository'), work = join(root, 'target/test/operation'), library = join(directory, 'rust/library');
  for (const path of [root, work, library]) mkdirSync(path, { recursive: true });
  const archives = new Map([['alpha-1.0.0', Buffer.from('official alpha fixture')], ['beta-2.0.0', Buffer.from('official beta fixture')]]);
  const sdk = lock([['alpha', '1.0.0', hash(archives.get('alpha-1.0.0'))]]);
  const std = lock([['alpha', '1.0.0', hash(archives.get('alpha-1.0.0'))], ['beta', '2.0.0', hash(archives.get('beta-2.0.0'))]]);
  writeFileSync(join(root, 'Cargo.lock'), sdk); writeFileSync(join(library, 'Cargo.lock'), std);
  for (const path of [join(root, 'Cargo.toml'), join(library, 'Cargo.toml')]) writeFileSync(path, 'fixture');
  const input = { CARGO: '/fixture/cargo', RUSTC: '/fixture/rustc' };
  const vendor = (_tool, args, cwd, environment) => {
    assert.equal(cwd, root); assert.equal(_tool, input.CARGO);
    assert.deepEqual(args, ['vendor', '--locked', '--versioned-dirs', '--manifest-path', join(root, 'Cargo.toml'),
      '--sync', join(library, 'Cargo.toml'), join(work, 'cargo/packages')]);
    assert.equal(environment.CARGO_HOME, join(work, 'cargo-download/home')); assert.equal(environment.RUSTC, input.RUSTC);
    assert.equal(environment.CARGO_NET_RETRY, '0'); assert.equal(environment.RUSTC_BOOTSTRAP, '1');
    assert.equal(environment.CARGO_REGISTRIES_CRATES_IO_INDEX, 'sparse+https://index.crates.io/');
    const cache = join(environment.CARGO_HOME, 'registry/cache/index.crates.io-123abc'); mkdirSync(cache, { recursive: true });
    for (const [coordinate, bytes] of archives) {
      writeFileSync(join(cache, coordinate + '.crate'), bytes);
      const packageRoot = join(work, 'cargo/packages', coordinate); mkdirSync(join(packageRoot, 'src'), { recursive: true });
      const files = { 'Cargo.toml': 'fixture package ' + coordinate, 'src/lib.rs': 'fixture source ' + coordinate };
      for (const [path, content] of Object.entries(files)) writeFileSync(join(packageRoot, path), content);
      writeFileSync(join(packageRoot, '.cargo-checksum.json'), JSON.stringify({ package: hash(bytes),
        files: Object.fromEntries(Object.entries(files).map(([path, content]) => [path, hash(content)])) }));
    }
  };
  return { root, work, library, input, sdk, std, archives, vendor,
    options: { expectedSDK: hash(sdk), expectedStd: hash(std), expectedCount: 2, execute: vendor } };
}
test('本仓真实原锁完整读取，联合锁精确去重且拒绝异源、缺摘要、异摘要及未知语法', () => {
  assert.equal(lockedPackages(readFileSync(new URL('../../Cargo.lock', import.meta.url), 'utf8')).size, 1531);
  const a = lock([['alpha', '1.0.0', 'a'.repeat(64)]]), b = lock([['alpha', '1.0.0', 'b'.repeat(64)]]);
  assert.equal(lockedUnion(a, a).size, 1);
  for (const text of [a.replace('registry+https://github.com/rust-lang/crates.io-index', 'git+https://example.com/sdk'),
    a.replace(/^checksum = .*\n/mu, ''), a.replace('a'.repeat(64), 'A'.repeat(64)), a + b.slice(header.length),
    a.replace('name = "alpha"', 'name = "alpha"\nname = "alpha"'), a + '[metadata]\nfixture = true\n',
    a.replace('source = ', 'unexpected = '), a.replace('1.0.0', '../outside')]) assert.throws(() => lockedPackages(text));
  assert.throws(() => lockedUnion(a, b), /异摘要/u);
});
test('双锁一次vendor准备准确独立离线配置，原锁保持逐字节不变且不能接管已有目录', context => {
  const f = fixture(context);
  const result = prepareOffline(f.root, f.work, f.input, f.library, f.options);
  assert.equal(result.CARGO_HOME, join(f.work, 'cargo/home'));
  assert.equal(readFileSync(join(result.CARGO_HOME, 'config.toml'), 'utf8'), '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
    + JSON.stringify(join(f.work, 'cargo/packages')) + '\n');
  assert.equal(readFileSync(join(f.root, 'Cargo.lock'), 'utf8'), f.sdk);
  assert.equal(readFileSync(join(f.library, 'Cargo.lock'), 'utf8'), f.std);
  verifyVendor(join(f.work, 'cargo/packages'), join(f.work, 'cargo-download/home'), lockedUnion(f.sdk, f.std));
  assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), /EEXIST/u);
});
test('缺锁、非获准原锁、错误联合数量与准备时两锁变化均失败', context => {
  for (const change of ['missing', 'different', 'count', 'sdk-during', 'std-during']) {
    const f = fixture(context);
    if (change === 'missing') rmSync(join(f.root, 'Cargo.lock'));
    if (change === 'different') writeFileSync(join(f.library, 'Cargo.lock'), f.std + '\n');
    if (change === 'count') f.options.expectedCount = 3;
    let calls = 0;
    f.options.execute = (...args) => { calls++; f.vendor(...args);
      if (change.endsWith('-during')) writeFileSync(join(change.startsWith('sdk-') ? f.root : f.library, 'Cargo.lock'), 'changed'); };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options));
    assert.equal(calls, change.endsWith('-during') ? 1 : 0);
  }
});
test('原包或展开清单缺失、多余、损坏、链接、越界及包摘要伪造均拒绝', context => {
  const cases = ['archive-digest', 'missing-archive', 'extra-archive', 'missing-package', 'extra-package', 'file-digest',
    'missing-file', 'extra-file', 'package-link', 'file-link', 'checksum-link', 'package-digest', 'escape'];
  for (const change of cases) {
    const f = fixture(context), packages = join(f.work, 'cargo/packages'), alpha = join(packages, 'alpha-1.0.0');
    const cache = join(f.work, 'cargo-download/home/registry/cache/index.crates.io-123abc');
    f.options.execute = (...args) => {
      f.vendor(...args);
      if (change === 'archive-digest') writeFileSync(join(cache, 'alpha-1.0.0.crate'), 'damaged');
      if (change === 'missing-archive') rmSync(join(cache, 'alpha-1.0.0.crate'));
      if (change === 'extra-archive') writeFileSync(join(cache, 'extra-1.0.0.crate'), 'extra');
      if (change === 'missing-package') rmSync(alpha, { recursive: true });
      if (change === 'extra-package') mkdirSync(join(packages, 'extra-1.0.0'));
      if (change === 'file-digest') writeFileSync(join(alpha, 'src/lib.rs'), 'damaged');
      if (change === 'missing-file') rmSync(join(alpha, 'src/lib.rs'));
      if (change === 'extra-file') writeFileSync(join(alpha, 'extra'), 'extra');
      if (change === 'package-link') { renameSync(alpha, join(f.work, 'linked-package')); symlinkSync(join(f.work, 'linked-package'), alpha); }
      if (change === 'file-link') { rmSync(join(alpha, 'src/lib.rs')); symlinkSync(join(alpha, 'Cargo.toml'), join(alpha, 'src/lib.rs')); }
      if (change === 'checksum-link') { renameSync(join(alpha, '.cargo-checksum.json'), join(f.work, 'linked-checksum')); symlinkSync(join(f.work, 'linked-checksum'), join(alpha, '.cargo-checksum.json')); }
      if (['package-digest', 'escape'].includes(change)) {
        const checksum = JSON.parse(readFileSync(join(alpha, '.cargo-checksum.json')));
        if (change === 'package-digest') checksum.package = 'f'.repeat(64);
        else checksum.files['../outside'] = 'a'.repeat(64);
        writeFileSync(join(alpha, '.cargo-checksum.json'), JSON.stringify(checksum));
      }
    };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), undefined, change);
  }
});
test('准备期间工作根或独立下载主目录被替换即失败', context => {
  for (const path of ['work', 'home']) {
    const f = fixture(context);
    f.options.execute = (...args) => {
      f.vendor(...args);
      const original = path === 'work' ? f.work : join(f.work, 'cargo-download/home');
      renameSync(original, original + '-old'); mkdirSync(original);
    };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), /被替换/u);
  }
});
test('官方Ubuntu Runner、本仓准确main push及独立根绑定，错误事实和链接根均拒绝', context => {
  const f = fixture(context), event = { before: 'a'.repeat(40), after: 'b'.repeat(40), ref: 'refs/heads/main', repository: { full_name: 'crcfrcn/polkadot-sdk' } };
  const input = { GITHUB_ACTIONS: 'true', RUNNER_ENVIRONMENT: 'github-hosted', RUNNER_OS: 'Linux', RUNNER_ARCH: 'X64',
    GITHUB_EVENT_NAME: 'push', GITHUB_REPOSITORY: 'crcfrcn/polkadot-sdk', GITHUB_REF: event.ref, GITHUB_SHA: event.after,
    GITHUB_WORKSPACE: f.root, TATAGATE_WORK: f.work };
  const facts = { expectedWork: f.work, platform: 'linux', arch: 'x64', os: 'ID=ubuntu\nVERSION_ID="24.04"\n', event };
  assert.equal(remoteContext(f.root, f.work, input, facts), event);
  for (const key of ['GITHUB_ACTIONS', 'RUNNER_ENVIRONMENT', 'RUNNER_OS', 'RUNNER_ARCH', 'GITHUB_EVENT_NAME',
    'GITHUB_REPOSITORY', 'GITHUB_REF', 'GITHUB_SHA', 'TATAGATE_WORK', 'GITHUB_WORKSPACE']) {
    assert.throws(() => remoteContext(f.root, f.work, { ...input, [key]: 'wrong' }, facts));
  }
  for (const change of [{ platform: 'darwin' }, { arch: 'arm64' }, { os: 'ID=ubuntu\nVERSION_ID="22.04"\n' },
    { expectedWork: f.root }, { event: { ...event, after: 'c'.repeat(40) } }, { event: { ...event, before: event.after } }]) {
    assert.throws(() => remoteContext(f.root, f.work, input, { ...facts, ...change }));
  }
  symlinkSync(f.work, f.work + '-link');
  assert.throws(() => remoteContext(f.root, f.work + '-link', { ...input, TATAGATE_WORK: f.work + '-link' }, { ...facts, expectedWork: f.work + '-link' }));
});
test('远端工具版本、同一Rust及Clang对象和完整构建选项不能替换', context => {
  const f = fixture(context), rust = join(f.work, 'tools/rust'), node = join(f.work, 'tools/node'), clang = join(f.work, 'tools/llvm/bin/clang');
  const cmake = join(f.work, 'tools/cmake'), libclang = join(f.work, 'tools/llvm/lib');
  const input = { CARGO: join(rust, 'bin/cargo'), TATAGATE_CARGO: join(rust, 'bin/cargo'), RUSTC: join(rust, 'bin/rustc'),
    TATAGATE_RUSTC: join(rust, 'bin/rustc'), RUSTDOC: join(rust, 'bin/rustdoc'), TATAGATE_NODE: node, CC: clang,
    CXX: join(f.work, 'tools/llvm/bin/clang++'), CMAKE_COMMAND: cmake, LIBCLANG_PATH: libclang,
    PROTOC: join(f.work, 'tools/protoc/bin/protoc'), PRODUCT_GIT_BIN: join(f.work, 'tools/git/payload/bin/git'),
    TATAGATE_ACTIONLINT: join(f.work, 'tools/actionlint/actionlint'), CARGO_BUILD_JOBS: '2',
    CARGO_PROFILE_DEV_DEBUG: '0', CARGO_PROFILE_TEST_DEBUG: '0', CARGO_INCREMENTAL: '0',
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: '--cfg=rustix_use_libc' };
  const versions = new Map([[node, 'v25.2.1'], [input.CARGO, 'cargo 1.97.1 fixture'], [input.RUSTC, 'rustc 1.97.1 fixture'],
    [input.RUSTDOC, 'rustdoc 1.97.1 fixture'], [clang, 'Ubuntu clang version 18.1.3 fixture'], [cmake, 'cmake version 3.31.6'],
    [input.PROTOC, 'libprotoc 35.0'], [input.PRODUCT_GIT_BIN, 'git version 2.54.0'], [input.TATAGATE_ACTIONLINT, '1.7.12\nbuild info'],
    [join(f.work, 'tools/solidity/bin/solc'), 'solc, the solidity compiler commandline interface\nVersion: 0.8.30+commit.73712a01.Linux.g++'],
    [join(f.work, 'tools/solidity/bin/resolc'), 'Solidity frontend for the revive compiler version 1.0.0+commit.b080c1d.llvm-18.1.8']]);
  for (const path of versions.keys()) { mkdirSync(join(path, '..'), { recursive: true }); writeFileSync(path, 'fixture', { mode: 0o755 }); }
  mkdirSync(libclang, { recursive: true }); writeFileSync(join(libclang, 'libclang.so.1'), 'fixture');
  symlinkSync(clang, input.CXX);
  const options = { execute: tool => versions.get(tool), expectedRust: rust, expectedNode: node, expectedClang: clang, expectedCMake: cmake, expectedLibclang: libclang };
  assert.equal(remoteTools(f.root, f.work, input, options), join(rust, 'lib/rustlib/src/rust/library'));
  for (const key of Object.keys(input)) assert.throws(() => remoteTools(f.root, f.work, { ...input, [key]: 'wrong' }, options), undefined, key);
  const missingFlag = { ...input }; delete missingFlag.CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS;
  assert.throws(() => remoteTools(f.root, f.work, missingFlag, options), /交付不符/u);
  for (const tool of versions.keys()) assert.throws(() => remoteTools(f.root, f.work, input, { ...options, execute: value => value === tool ? '0.0.0' : versions.get(value) }));
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER', 'RUSTUP_TOOLCHAIN',
    'RUSTFLAGS', 'CARGO_ENCODED_RUSTFLAGS']) assert.throws(() => remoteTools(f.root, f.work, { ...input, [key]: '0' }, options), /拒绝/u);
  const hardlink = input.PRODUCT_GIT_BIN + '-hardlink';
  linkSync(input.PRODUCT_GIT_BIN, hardlink);
  assert.throws(() => remoteTools(f.root, f.work, input, options), error =>
    error.message === 'SDK准备文件不是独占普通文件：' + input.PRODUCT_GIT_BIN);
  rmSync(hardlink);
  assert.equal(remoteTools(f.root, f.work, input, options), join(rust, 'lib/rustlib/src/rust/library'));
});
test('远端首次与失败后的补修均覆盖合同初始提交以来的改动，非法区间拒绝', () => {
  const after = 'b'.repeat(40), failed = 'a93ed7b73119fdf4edb512943dba616bd9d53ba1';
  for (const before of [contract.initial_sha, failed]) {
    assert.deepEqual(remoteRange(contract, { before, after }), { base: contract.initial_sha, head: after });
  }
  assert.throws(() => remoteRange({ ...contract, checks: [] }, { before: failed, after }));
  for (const event of [{ before: 'main', after }, { before: failed, after: 'main' },
    { before: after, after }, { before: failed, after: contract.initial_sha }]) {
    assert.throws(() => remoteRange(contract, event));
  }
});
test('宿主生成器变更同时触发原生、实际WASM执行器及文档测试，普通改动不增加范围', () => {
  const path = 'substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs';
  assert.deepEqual(hostChecks(['substrate/frame/revive/src/lib.rs']), []);
  assert.deepEqual(hostChecks([path]), [['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface-test', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--doc']]);
});
test('错仓、错来源、缺检查与非法区间拒绝', () => {
  for (const change of [{ repository: 'citizenchain' }, { upstream: 'other/polkadot-sdk' }, { checks: [] }, { upstream_base: 'main' }, { schema: 2 }]) {
    assert.throws(() => gateContract({ ...contract, ...change }));
  }
  for (const pair of [['a', 'b'], ['a'.repeat(40), 'a'.repeat(40)], [null, 'b'.repeat(40)], ['A'.repeat(40), 'b'.repeat(40)]]) {
    assert.throws(() => gateRange(...pair));
  }
});
test('绝对路径、空段及路径穿越拒绝', () => {
  for (const path of ['', '/substrate/lib.rs', '../lib.rs', 'a/../b', 'a//b', 'a\\b']) assert.throws(() => gatePath(path));
});

test('真实离线子Cargo拒绝父cfg泄漏，WASM命令隔离后按自身目标重新生成', context => {
  const cargo = process.env.TATAGATE_CARGO, rustc = process.env.TATAGATE_RUSTC;
  assert.ok(cargo?.startsWith('/') && rustc?.startsWith('/'), '回归需要SDK公开交付的同一Rust对象');
  assert.equal(realpathSync(cargo), cargo); assert.equal(realpathSync(rustc), rustc);
  assert.equal(dirname(cargo), dirname(rustc));
  for (const [tool, expected] of [[cargo, 'cargo 1.97.1 '], [rustc, 'rustc 1.97.1 ']]) {
    const result = spawnSync(tool, ['--version'], { encoding: 'utf8', timeout: 10_000 });
    assert.equal(result.status, 0); assert.ok(result.stdout.startsWith(expected));
  }
  const source = readFileSync(new URL('../../substrate/utils/wasm-builder/src/wasm_project.rs', import.meta.url), 'utf8');
  assert.match(source, /\.env_remove\("CARGO_ENCODED_RUSTFLAGS"\)[\s\S]*?\.env_remove\("CARGO_CFG_RUSTIX_USE_LIBC"\)[\s\S]*?\.env_remove\("RUSTC"\)/u);
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-child-cargo-cfg-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  mkdirSync(join(directory, 'src')); mkdirSync(join(directory, 'home'));
  const manifest = '[package]\nname = "sdk-child-cargo-cfg"\nversion = "0.1.0"\nedition = "2021"\n[workspace]\n';
  const frozenLock = 'version = 4\n\n[[package]]\nname = "sdk-child-cargo-cfg"\nversion = "0.1.0"\n';
  writeFileSync(join(directory, 'Cargo.toml'), manifest); writeFileSync(join(directory, 'Cargo.lock'), frozenLock);
  writeFileSync(join(directory, 'src/lib.rs'), '#![no_std]\n');
  // 零外部依赖的真实构建脚本独立比较环境与编译cfg，不能以字符串断言代替子Cargo行为。
  writeFileSync(join(directory, 'build.rs'), 'fn main() { assert_eq!(std::env::var_os("CARGO_CFG_RUSTIX_USE_LIBC").is_some(), cfg!(rustix_use_libc), "父cfg泄漏到子Cargo"); }\n');
  // 构建脚本仍需宿主链接器及SDK；保留调用方已交付的公开输入，不从系统PATH补工具。
  const hostInputs = Object.fromEntries(['DEVELOPER_DIR', 'SDKROOT',
    'CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER', 'CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER']
    .flatMap(key => process.env[key] ? [[key, process.env[key]]] : []));
  for (const inherited of [true, false]) {
    const environment = { ...hostInputs, PATH: process.env.PATH, CARGO_HOME: join(directory, 'home'), CARGO_NET_OFFLINE: 'true',
      CARGO_TARGET_DIR: join(directory, inherited ? 'leaked-target' : 'isolated-target'),
      RUSTC: rustc, CARGO: cargo, RUSTFLAGS: '', RUSTC_BOOTSTRAP: '1' };
    if (inherited) environment.CARGO_CFG_RUSTIX_USE_LIBC = '';
    const result = spawnSync(cargo, ['check', '--locked', '--offline', '--target', 'wasm32-unknown-unknown'],
      { cwd: directory, env: environment, encoding: 'utf8', timeout: 60_000 });
    assert.equal(result.error, undefined);
    assert.equal(result.status, inherited ? 101 : 0, result.stderr);
    assert.equal(result.stderr.includes('panicked at') && result.stderr.includes('父cfg泄漏到子Cargo'), inherited);
    assert.equal(readFileSync(join(directory, 'Cargo.lock'), 'utf8'), frozenLock);
  }
});

test('完整门禁使用同一Rust对象和独立离线环境，拒绝跳过及工具替换', context => {
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-gate-environment-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  const root = join(directory, 'repository'), work = join(root, 'target/test/gate');
  const home = join(work, 'cargo/home'), packages = join(work, 'cargo/packages');
  const bin = join(directory, 'rust/bin');
  for (const path of [root, work, home, packages, bin]) mkdirSync(path, { recursive: true });
  for (const tool of ['cargo', 'rustc']) writeFileSync(join(bin, tool), 'fixture', { mode: 0o755 });
  const config = '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
    + JSON.stringify(packages) + '\n';
  writeFileSync(join(home, 'config.toml'), config);
  const input = { TATAGATE_CARGO: join(bin, 'cargo'), TATAGATE_RUSTC: join(bin, 'rustc'),
    CARGO: join(bin, 'cargo'), RUSTC: join(bin, 'rustc'), CARGO_HOME: home };
  const execute = tool => tool.endsWith('/cargo') ? 'cargo 1.97.1 fixture' : 'rustc 1.97.1 fixture';
  const result = gateEnvironment(root, work, input, { execute });
  assert.equal(result.CARGO_NET_OFFLINE, 'true'); assert.equal(result.CARGO_TARGET_DIR, join(work, 'cargo-target'));
  assert.equal(result.RUSTC, input.RUSTC); assert.equal(result.WASM_BUILD_STD, '1');
  assert.equal(result.WASM_BUILD_WORKSPACE_HINT, root);
  assert.equal(gateEnvironment(root, work, { ...input, WASM_BUILD_WORKSPACE_HINT: '/other/repository' },
    { execute }).WASM_BUILD_WORKSPACE_HINT, root);
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTUP_TOOLCHAIN']) {
    assert.throws(() => gateEnvironment(root, work, { ...input, [key]: '0' }, { execute }), /拒绝/u);
  }
  for (const changes of [{ RUSTC: '/other/rustc' }, { CARGO: '/other/cargo' }, { CARGO_HOME: root }]) {
    assert.throws(() => gateEnvironment(root, work, { ...input, ...changes }, { execute }));
  }
  assert.throws(() => gateEnvironment(root, root, input, { execute }), /中间物/u);
  const outside=join(directory,'outside'),build=join(root,'target/build/foreign');mkdirSync(outside);mkdirSync(build,{recursive:true});
  for(const foreign of [outside,build])assert.throws(()=>gateEnvironment(root,foreign,input,{execute}),/中间物/u);
  assert.throws(() => gateEnvironment(root, work, input, { execute: () => 'rustc 1.97.0 fixture' }), /版本/u);
  symlinkSync(home, join(directory, 'home-link'));
  assert.throws(() => gateEnvironment(root, work, { ...input, CARGO_HOME: join(directory, 'home-link') }, { execute }));
  writeFileSync(join(home, 'config.toml'), config.replace('offline = true', 'offline = false'));
  assert.throws(() => gateEnvironment(root, work, input, { execute }), /目录源/u);
});

// Git正例使用已登记工具创建真实对象；来源字符串只是隔离夹具，不联网。
function gitFixture(context) {
  const f = fixture(context), home = join(f.work, 'git-home'), checkout = join(home, 'git/checkouts/fixture/revision');
  mkdirSync(join(home, 'git/db'), { recursive: true }); mkdirSync(checkout, { recursive: true });
  const git = process.env.PRODUCT_GIT_BIN;
  assert.ok(git?.startsWith('/'), '门禁测试必须传入已登记Git绝对入口');
  const execute = (tool, args, cwd, env) => {
    const result = spawnSync(tool, args, { cwd, env, encoding: 'utf8' });
    if (result.error || result.status !== 0) throw new Error(result.error?.message ?? result.stderr);
    return result.stdout.trim();
  };
  const input = { ...process.env, PRODUCT_GIT_BIN: git, CARGO: '/fixture/cargo', RUSTC: '/fixture/rustc',
    GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', GIT_NO_REPLACE_OBJECTS: '1' };
  const run = args => execute(git, ['-C', checkout, ...args], f.root, input);
  run(['init', '--template=']);
  const manifest = join(checkout, 'Cargo.toml');
  writeFileSync(manifest, '[package]\nname = "fixture"\nversion = "1.0.0"\n');
  run(['add', 'Cargo.toml']);
  run(['-c', 'user.name=SDK Test', '-c', 'user.email=sdk-test@example.invalid', 'commit', '-m', 'fixture']);
  const revision = run(['rev-parse', 'HEAD']);
  const source = 'git+https://github.com/example/fixture.git?rev=' + revision + '#' + revision;
  const union = new Map([['fixture-1.0.0', { name: 'fixture', version: '1.0.0', source }]]);
  const metadata = { packages: [{ name: 'fixture', version: '1.0.0', source, manifest_path: manifest }] };
  return { ...f, home, checkout, manifest, revision, source, union, metadata, input, execute, run };
}
test('固定Git锁只接受准确HTTPS来源和同一40位提交，异源及伪造摘要失败', () => {
  const revision = 'a'.repeat(40), source = 'git+https://github.com/example/fixture.git?rev=' + revision + '#' + revision;
  assert.deepEqual(lockedGitSource(source), { repository: 'https://github.com/example/fixture.git', revision });
  const gitLock = header + '[[package]]\nname = "fixture"\nversion = "1.0.0"\nsource = ' + JSON.stringify(source) + '\n\n';
  assert.equal(lockedUnion(gitLock, gitLock).size, 1);
  assert.equal(lockedPackages(gitLock).get('fixture-1.0.0').source, source);
  for (const invalid of [source.replace('https:', 'http:'), source.replace('github.com', 'user@github.com'),
    source.replace('github.com', 'github.com:443'), source.replace('?rev=', '?branch='), source.replace('#' + revision, '#' + 'b'.repeat(40)),
    source.replace(revision, 'main'), source.replace('.git?', '?'), source.replace('example/', 'example/../')]) {
    assert.throws(() => lockedGitSource(invalid));
  }
  assert.throws(() => lockedPackages(gitLock + 'checksum = "' + 'a'.repeat(64) + '"\n'), /伪造/u);
  assert.throws(() => lockedUnion(gitLock, lock([['fixture', '1.0.0', 'a'.repeat(64)]])), /异源/u);
});
test('真实固定Git检出接受Cargo标记，拒绝污染、错误HEAD、metadata及目录越界', context => {
  const f = gitFixture(context), options = { execute: f.execute, metadata: f.metadata };
  verifyGitCache(f.root, f.home, f.union, f.input, options);
  writeFileSync(join(f.checkout, '.cargo-ok'), '');
  verifyGitCache(f.root, f.home, f.union, f.input, options);
  writeFileSync(join(f.checkout, 'extra.rs'), 'untracked');
  assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input, options), /额外文件/u);
  rmSync(join(f.checkout, 'extra.rs'));
  const original = readFileSync(f.manifest);
  writeFileSync(f.manifest, 'dirty');
  assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input, options));
  writeFileSync(f.manifest, original);
  for (const change of [{ version: '2.0.0' }, { source: f.source.replaceAll(f.revision, 'b'.repeat(40)) },
    { manifest_path: join(f.root, 'Cargo.toml') }]) {
    assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input,
      { ...options, metadata: { packages: [{ ...f.metadata.packages[0], ...change }] } }));
  }
  assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input,
    { ...options, metadata: { packages: [f.metadata.packages[0], f.metadata.packages[0]] } }), /坐标/u);
  renameSync(f.manifest, f.manifest + '-saved'); symlinkSync(f.manifest + '-saved', f.manifest);
  assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input, options));
  rmSync(f.manifest); renameSync(f.manifest + '-saved', f.manifest);
  f.run(['-c', 'user.name=SDK Test', '-c', 'user.email=sdk-test@example.invalid', 'commit', '--allow-empty', '-m', 'wrong head']);
  assert.throws(() => verifyGitCache(f.root, f.home, f.union, f.input, options), /提交不符/u);
});

test('Git与registry同次准备后仍从原锁Git检出消费，复制缓存和移除冗余vendor包均受验真', context => {
  const f = gitFixture(context);
  const sdk = f.sdk + '[[package]]\nname = "fixture"\nversion = "1.0.0"\nsource = ' + JSON.stringify(f.source) + '\n\n';
  writeFileSync(join(f.root, 'Cargo.lock'), sdk);
  let metadataCalls = 0;
  const execute = (tool, args, cwd, environment) => {
    if (tool === f.input.CARGO && args[0] === 'vendor') {
      f.vendor(tool, args, cwd, environment);
      cpSync(join(f.home, 'git'), join(environment.CARGO_HOME, 'git'), { recursive: true });
      mkdirSync(join(f.work, 'cargo/packages/fixture-1.0.0'));
      return '';
    }
    if (tool === f.input.CARGO && args[0] === 'metadata') {
      metadataCalls++;
      assert.deepEqual(args, ['metadata', '--locked', '--offline', '--format-version', '1']);
      assert.equal(environment.CARGO_NET_OFFLINE, 'true');
      return JSON.stringify({ packages: [{ ...f.metadata.packages[0],
        manifest_path: join(environment.CARGO_HOME, 'git/checkouts/fixture/revision/Cargo.toml') }] });
    }
    return f.execute(tool, args, cwd, environment);
  };
  const result = prepareOffline(f.root, f.work, f.input, f.library,
    { ...f.options, expectedSDK: hash(sdk), expectedCount: 3, execute });
  assert.equal(metadataCalls, 2);
  assert.deepEqual(readFileSync(join(result.CARGO_HOME, 'git/checkouts/fixture/revision/Cargo.toml')), readFileSync(f.manifest));
  assert.throws(() => readFileSync(join(f.work, 'cargo/packages/fixture-1.0.0/Cargo.toml')), /ENOENT/u);
  assert.equal(readFileSync(join(f.root, 'Cargo.lock'), 'utf8'), sdk);
  assert.doesNotMatch(readFileSync(join(result.CARGO_HOME, 'config.toml'), 'utf8'), /source[.]git|patch|fixture/u);
});

// 完整执行的判定调用真实汇总函数，不以零退出码代替非空、无跳过结果。
test('SDK测试汇总拒绝空执行、跳过、取消和不相等计数',async()=>{
 const {successfulTestSummary,hasFirstPartyTemporaryComments}=await import('./index.mjs');
 const good={success:true,counts:{tests:2,passed:2,failed:0,skipped:0,cancelled:0,todo:0}};
 assert.equal(successfulTestSummary(good),true);
 for(const change of [{tests:0,passed:0},{passed:1},{failed:1},{skipped:1},{cancelled:1},{todo:1}])assert.ok(!successfulTestSummary({...good,counts:{...good.counts,...change}}));
 assert.equal(hasFirstPartyTemporaryComments('code.rs','let x="TODO";'),false);
 assert.equal(hasFirstPartyTemporaryComments('code.rs','// TODO upstream\n','// TODO upstream\n'),false);
 assert.equal(hasFirstPartyTemporaryComments('code.rs','// TODO upstream\n// TODO upstream\n','// TODO upstream\n'),true);
 assert.throws(()=>gateContract({...contract,github_repository:'foreign/sdk'}));
 assert.throws(()=>gateContract({...contract,node_tests:[]}));
});

// 结果协议夹具只验证同一SDK核验接口；真实affected crate及WASM由完整门禁执行。
test('SDK功能目标闭合，实际结果拒绝空跑、过滤、跳过和失败',async()=>{
 const {sdkFunctionalResult}=await import('./index.mjs'),output='test feature ... ok\ntest result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out;';
 assert.deepEqual(sdkFunctionalResult(output,{target:'owned-crate'}),{target:'owned-crate',type:'all-targets',tests:1,status:'success'});
 for(const invalid of ['',output.replace('1 passed','0 passed'),output.replace('0 ignored','1 ignored'),output.replace('0 filtered out','1 filtered out'),output.replace('ok.','FAILED.')])assert.throws(()=>sdkFunctionalResult(invalid,{target:'owned-crate'}));
 assert.equal(sdkFunctionalResult(output.replace('1 passed','0 passed'),{target:'owned-crate',documentation:true}).tests,0);
 for(const targets of [[],[...contract.functional_targets,'undeclared'],contract.functional_targets.slice(1)])assert.throws(()=>gateContract({...contract,functional_targets:targets}));
});

import {tataGateOwner,tataGateContext,tataGateValidateWorkflow,tataGateCleanupPlan,tataGateCleanup} from './index.mjs';
import {readFileSync as tataGateRead} from 'node:fs';
  test('塔塔门禁Workflow只允许本仓push，门禁和清理同处唯一文件',()=>{
    const source=tataGateRead(new URL('../workflows/tatagate.yml',import.meta.url),'utf8');
    assert.equal(tataGateValidateWorkflow(source),true);
    for(const invalid of [source.replace('branches: [main]','branches: [other]'),source.replace('needs: [gate]','needs: [other]'),source.replace('continue-on-error: true','continue-on-error: false')])assert.throws(()=>tataGateValidateWorkflow(invalid));
  });
  test('塔塔门禁成功清旧成功、失败清旧失败，活动、未来和其它流程均保留',()=>{
    const row=(id,conclusion='success',status='completed')=>({id,run_number:id,run_attempt:1,path:'.github/workflows/tatagate.yml',event:'push',head_branch:'main',head_sha:'a'.repeat(40),repository:{full_name:tataGateOwner},created_at:'2026-01-01T00:00:00Z',status,conclusion});
    const current=row(9,null,'in_progress'),rows=[row(1),row(2,'failure'),row(3,null,'in_progress'),row(10),{...row(4),path:'.github/workflows/release-sdk.yml'},{...row(5),repository:{full_name:'example/other'}}];
    assert.deepEqual(tataGateCleanupPlan(rows,current,'success').map(x=>x.id),[1]);
    assert.deepEqual(tataGateCleanupPlan(rows,current,'failed').map(x=>x.id),[2]);
  });
  test('塔塔门禁删除逐项回查，清理失败和重跑变化均不能伪报完成',async()=>{
    const current={id:9,run_number:9,run_attempt:1,path:'.github/workflows/tatagate.yml',event:'push',head_branch:'main',head_sha:'a'.repeat(40),repository:{full_name:tataGateOwner},created_at:'2026-01-02T00:00:00Z',status:'in_progress',conclusion:null};
    const old={...current,id:1,run_number:1,status:'completed',conclusion:'success',created_at:'2026-01-01T00:00:00Z'};
    for(const mode of ['success','readback','rerun']){
      let deleted=false;const api=async(path,options={})=>{
        if(path==='actions/runs/9')return current;
        if(path.startsWith('actions/workflows/'))return {total_count:1,workflow_runs:[old]};
        if(options.method==='DELETE'){deleted=true;return null;}
        if(path==='actions/runs/1')return mode==='rerun'?{...old,run_attempt:2}:deleted&&mode==='success'?null:old;
        throw Error('错误清理路径');
      };
      if(mode==='success')assert.deepEqual(await tataGateCleanup('success',{id:9,sha:current.head_sha},api),[1]);
      else await assert.rejects(tataGateCleanup('success',{id:9,sha:current.head_sha},api),/回查失败|已变化/u);
      if(mode==='rerun')assert.equal(deleted,false);
    }
  });

import {execFileSync as tataGateExec} from 'node:child_process';
test('GitHub门禁工具供给使用公开固定test根，离线验收使用其独立子目录',async()=>{
  const {fileURLToPath}=await import('node:url');
  const {tataGateResourceRoots}=await import('./index.mjs'),{checkWork,testRoot}=await import('../../scripts/build.mjs');
  const source=fileURLToPath(new URL('../..',import.meta.url));
  const roots=tataGateResourceRoots(source);
  assert.equal(checkWork(roots.supply),testRoot());
  assert.equal(roots.work,join(roots.supply,'tatagate'));
  assert.throws(()=>checkWork(roots.work),/工作根/u);
});
  test('GitHub门禁接受准确提交的detached检出，错仓、错SHA和错误Workflow拒绝',async()=>{
    const {mkdtempSync,mkdirSync,writeFileSync,rmSync,realpathSync}=await import('node:fs');
    const {tmpdir}=await import('node:os'),{join}=await import('node:path');
    const directory=mkdtempSync(join(realpathSync(tmpdir()),'tata-gate-context-'));
    try{
      const git=process.env.PRODUCT_GIT_BIN||'/usr/bin/git';
      const invoke=args=>tataGateExec(git,['-c','core.hooksPath=/dev/null','-c','user.name=Tata Gate Fixture','-c','user.email=fixture@example.invalid','-C',directory,...args],{encoding:'utf8'}).trim();
      invoke(['init','--quiet','--initial-branch=main']);invoke(['remote','add','origin','https://github.com/'+tataGateOwner+'.git']);
      writeFileSync(join(directory,'file'),'first');invoke(['add','file']);invoke(['commit','--quiet','-m','first']);const before=invoke(['rev-parse','HEAD']);
      writeFileSync(join(directory,'file'),'second');invoke(['add','file']);invoke(['commit','--quiet','-m','second']);const after=invoke(['rev-parse','HEAD']);
      invoke(['checkout','--quiet','--detach',after]);
      const input={GITHUB_ACTIONS:'true',GITHUB_JOB:'gate',GITHUB_EVENT_NAME:'push',GITHUB_REPOSITORY:tataGateOwner,GITHUB_REF:'refs/heads/main',GITHUB_WORKSPACE:directory,GITHUB_SHA:after,
        GITHUB_WORKFLOW_REF:tataGateOwner+'/.github/workflows/tatagate.yml@refs/heads/main',PRODUCT_GIT_BIN:git};
      const event={repository:{full_name:tataGateOwner},ref:'refs/heads/main',before,after};
      assert.equal(tataGateContext(directory,input,event).after,after);
      assert.throws(()=>tataGateContext(directory,input,{...event,before:'a'.repeat(40)}),/祖先/u);
      writeFileSync(join(directory,'late'),'new change');assert.throws(()=>tataGateContext(directory,input,event),/未提交改动/u);rmSync(join(directory,'late'));
      for(const changed of [{...input,GITHUB_SHA:before},{...input,GITHUB_REPOSITORY:'example/other'},{...input,GITHUB_WORKFLOW_REF:tataGateOwner+'/.github/workflows/release-sdk.yml@refs/heads/main'}])assert.throws(()=>tataGateContext(directory,changed,event));
    }finally{rmSync(directory,{recursive:true,force:true});}
  });
