// 正常、失败及边界测试验证同一公开SDK门禁，不依赖私有资料或其它产品。
import assert from 'node:assert/strict';
import test from 'node:test';
import { gateContract, gatePath, gateRange, gateEnvironment, lockedPackages, lockedUnion, remoteContext,
  remoteTools, prepareOffline, verifyVendor, hostChecks, remoteRange } from './index.mjs';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, realpathSync, rmSync, symlinkSync, renameSync, linkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';
const contract = JSON.parse(readFileSync(new URL('./contracts.json', import.meta.url), 'utf8'));
test('准确SDK来源与提交区间有效', () => {
  assert.equal(gateContract(contract).repository, 'polkadot-sdk');
  assert.deepEqual(gateRange('a'.repeat(40), 'b'.repeat(40)), { base: 'a'.repeat(40), head: 'b'.repeat(40) });
  assert.equal(gatePath('substrate/frame/revive/src/lib.rs'), 'substrate/frame/revive/src/lib.rs');
});

const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const header = '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n';
const lock = entries => header + entries.map(([name, version, checksum]) => '[[package]]\nname = ' + JSON.stringify(name)
  + '\nversion = ' + JSON.stringify(version) + '\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = '
  + JSON.stringify(checksum) + '\n\n').join('');
function fixture(context) {
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-remote-preparation-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  const root = join(directory, 'repository'), work = join(directory, 'operation'), library = join(directory, 'rust/library');
  for (const path of [root, work, library]) mkdirSync(path, { recursive: true });
  const archives = new Map([['alpha-1.0.0', Buffer.from('official alpha fixture')], ['beta-2.0.0', Buffer.from('official beta fixture')]]);
  const sdk = lock([['alpha', '1.0.0', hash(archives.get('alpha-1.0.0'))]]);
  const std = lock([['alpha', '1.0.0', hash(archives.get('alpha-1.0.0'))], ['beta', '2.0.0', hash(archives.get('beta-2.0.0'))]]);
  writeFileSync(join(root, 'Cargo.lock'), sdk); writeFileSync(join(library, 'Cargo.lock'), std);
  for (const path of [join(root, 'Cargo.toml'), join(library, 'Cargo.toml')]) writeFileSync(path, 'fixture');
  const input = { CARGO: '/fixture/cargo', RUSTC: '/fixture/rustc' };
  const vendor = (_tool, args, cwd, environment) => {
    assert.equal(cwd, root); assert.equal(_tool, input.CARGO);
    assert.deepEqual(args, ['vendor', '--locked', '--versioned-dirs', '--manifest-path', join(root, 'Cargo.toml'),
      '--sync', join(library, 'Cargo.toml'), join(work, 'cargo/packages')]);
    assert.equal(environment.CARGO_HOME, join(work, 'cargo-download/home')); assert.equal(environment.RUSTC, input.RUSTC);
    assert.equal(environment.CARGO_NET_RETRY, '0'); assert.equal(environment.RUSTC_BOOTSTRAP, '1');
    assert.equal(environment.CARGO_REGISTRIES_CRATES_IO_INDEX, 'sparse+https://index.crates.io/');
    const cache = join(environment.CARGO_HOME, 'registry/cache/index.crates.io-123abc'); mkdirSync(cache, { recursive: true });
    for (const [coordinate, bytes] of archives) {
      writeFileSync(join(cache, coordinate + '.crate'), bytes);
      const packageRoot = join(work, 'cargo/packages', coordinate); mkdirSync(join(packageRoot, 'src'), { recursive: true });
      const files = { 'Cargo.toml': 'fixture package ' + coordinate, 'src/lib.rs': 'fixture source ' + coordinate };
      for (const [path, content] of Object.entries(files)) writeFileSync(join(packageRoot, path), content);
      writeFileSync(join(packageRoot, '.cargo-checksum.json'), JSON.stringify({ package: hash(bytes),
        files: Object.fromEntries(Object.entries(files).map(([path, content]) => [path, hash(content)])) }));
    }
  };
  return { root, work, library, input, sdk, std, archives, vendor,
    options: { expectedSDK: hash(sdk), expectedStd: hash(std), expectedCount: 2, execute: vendor } };
}
test('本仓真实原锁完整读取，联合锁精确去重且拒绝异源、缺摘要、异摘要及未知语法', () => {
  assert.equal(lockedPackages(readFileSync(new URL('../../Cargo.lock', import.meta.url), 'utf8')).size, 1531);
  const a = lock([['alpha', '1.0.0', 'a'.repeat(64)]]), b = lock([['alpha', '1.0.0', 'b'.repeat(64)]]);
  assert.equal(lockedUnion(a, a).size, 1);
  for (const text of [a.replace('registry+https://github.com/rust-lang/crates.io-index', 'git+https://example.com/sdk'),
    a.replace(/^checksum = .*\n/mu, ''), a.replace('a'.repeat(64), 'A'.repeat(64)), a + b.slice(header.length),
    a.replace('name = "alpha"', 'name = "alpha"\nname = "alpha"'), a + '[metadata]\nfixture = true\n',
    a.replace('source = ', 'unexpected = '), a.replace('1.0.0', '../outside')]) assert.throws(() => lockedPackages(text));
  assert.throws(() => lockedUnion(a, b), /异摘要/u);
});
test('双锁一次vendor准备准确独立离线配置，原锁保持逐字节不变且不能接管已有目录', context => {
  const f = fixture(context);
  const result = prepareOffline(f.root, f.work, f.input, f.library, f.options);
  assert.equal(result.CARGO_HOME, join(f.work, 'cargo/home'));
  assert.equal(readFileSync(join(result.CARGO_HOME, 'config.toml'), 'utf8'), '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
    + JSON.stringify(join(f.work, 'cargo/packages')) + '\n');
  assert.equal(readFileSync(join(f.root, 'Cargo.lock'), 'utf8'), f.sdk);
  assert.equal(readFileSync(join(f.library, 'Cargo.lock'), 'utf8'), f.std);
  verifyVendor(join(f.work, 'cargo/packages'), join(f.work, 'cargo-download/home'), lockedUnion(f.sdk, f.std));
  assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), /EEXIST/u);
});
test('缺锁、非获准原锁、错误联合数量与准备时两锁变化均失败', context => {
  for (const change of ['missing', 'different', 'count', 'sdk-during', 'std-during']) {
    const f = fixture(context);
    if (change === 'missing') rmSync(join(f.root, 'Cargo.lock'));
    if (change === 'different') writeFileSync(join(f.library, 'Cargo.lock'), f.std + '\n');
    if (change === 'count') f.options.expectedCount = 3;
    let calls = 0;
    f.options.execute = (...args) => { calls++; f.vendor(...args);
      if (change.endsWith('-during')) writeFileSync(join(change.startsWith('sdk-') ? f.root : f.library, 'Cargo.lock'), 'changed'); };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options));
    assert.equal(calls, change.endsWith('-during') ? 1 : 0);
  }
});
test('原包或展开清单缺失、多余、损坏、链接、越界及包摘要伪造均拒绝', context => {
  const cases = ['archive-digest', 'missing-archive', 'extra-archive', 'missing-package', 'extra-package', 'file-digest',
    'missing-file', 'extra-file', 'package-link', 'file-link', 'checksum-link', 'package-digest', 'escape'];
  for (const change of cases) {
    const f = fixture(context), packages = join(f.work, 'cargo/packages'), alpha = join(packages, 'alpha-1.0.0');
    const cache = join(f.work, 'cargo-download/home/registry/cache/index.crates.io-123abc');
    f.options.execute = (...args) => {
      f.vendor(...args);
      if (change === 'archive-digest') writeFileSync(join(cache, 'alpha-1.0.0.crate'), 'damaged');
      if (change === 'missing-archive') rmSync(join(cache, 'alpha-1.0.0.crate'));
      if (change === 'extra-archive') writeFileSync(join(cache, 'extra-1.0.0.crate'), 'extra');
      if (change === 'missing-package') rmSync(alpha, { recursive: true });
      if (change === 'extra-package') mkdirSync(join(packages, 'extra-1.0.0'));
      if (change === 'file-digest') writeFileSync(join(alpha, 'src/lib.rs'), 'damaged');
      if (change === 'missing-file') rmSync(join(alpha, 'src/lib.rs'));
      if (change === 'extra-file') writeFileSync(join(alpha, 'extra'), 'extra');
      if (change === 'package-link') { renameSync(alpha, join(f.work, 'linked-package')); symlinkSync(join(f.work, 'linked-package'), alpha); }
      if (change === 'file-link') { rmSync(join(alpha, 'src/lib.rs')); symlinkSync(join(alpha, 'Cargo.toml'), join(alpha, 'src/lib.rs')); }
      if (change === 'checksum-link') { renameSync(join(alpha, '.cargo-checksum.json'), join(f.work, 'linked-checksum')); symlinkSync(join(f.work, 'linked-checksum'), join(alpha, '.cargo-checksum.json')); }
      if (['package-digest', 'escape'].includes(change)) {
        const checksum = JSON.parse(readFileSync(join(alpha, '.cargo-checksum.json')));
        if (change === 'package-digest') checksum.package = 'f'.repeat(64);
        else checksum.files['../outside'] = 'a'.repeat(64);
        writeFileSync(join(alpha, '.cargo-checksum.json'), JSON.stringify(checksum));
      }
    };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), undefined, change);
  }
});
test('准备期间工作根或独立下载主目录被替换即失败', context => {
  for (const path of ['work', 'home']) {
    const f = fixture(context);
    f.options.execute = (...args) => {
      f.vendor(...args);
      const original = path === 'work' ? f.work : join(f.work, 'cargo-download/home');
      renameSync(original, original + '-old'); mkdirSync(original);
    };
    assert.throws(() => prepareOffline(f.root, f.work, f.input, f.library, f.options), /被替换/u);
  }
});
test('官方Ubuntu Runner、本仓准确main push及独立根绑定，错误事实和链接根均拒绝', context => {
  const f = fixture(context), event = { before: 'a'.repeat(40), after: 'b'.repeat(40), ref: 'refs/heads/main', repository: { full_name: 'crcfrcn/polkadot-sdk' } };
  const input = { GITHUB_ACTIONS: 'true', RUNNER_ENVIRONMENT: 'github-hosted', RUNNER_OS: 'Linux', RUNNER_ARCH: 'X64',
    GITHUB_EVENT_NAME: 'push', GITHUB_REPOSITORY: 'crcfrcn/polkadot-sdk', GITHUB_REF: event.ref, GITHUB_SHA: event.after,
    GITHUB_WORKSPACE: f.root, TATAGATE_WORK: f.work };
  const facts = { expectedWork: f.work, platform: 'linux', arch: 'x64', os: 'ID=ubuntu\nVERSION_ID="24.04"\n', event };
  assert.equal(remoteContext(f.root, f.work, input, facts), event);
  for (const key of ['GITHUB_ACTIONS', 'RUNNER_ENVIRONMENT', 'RUNNER_OS', 'RUNNER_ARCH', 'GITHUB_EVENT_NAME',
    'GITHUB_REPOSITORY', 'GITHUB_REF', 'GITHUB_SHA', 'TATAGATE_WORK', 'GITHUB_WORKSPACE']) {
    assert.throws(() => remoteContext(f.root, f.work, { ...input, [key]: 'wrong' }, facts));
  }
  for (const change of [{ platform: 'darwin' }, { arch: 'arm64' }, { os: 'ID=ubuntu\nVERSION_ID="22.04"\n' },
    { expectedWork: f.root }, { event: { ...event, after: 'c'.repeat(40) } }, { event: { ...event, before: event.after } }]) {
    assert.throws(() => remoteContext(f.root, f.work, input, { ...facts, ...change }));
  }
  symlinkSync(f.work, f.work + '-link');
  assert.throws(() => remoteContext(f.root, f.work + '-link', { ...input, TATAGATE_WORK: f.work + '-link' }, { ...facts, expectedWork: f.work + '-link' }));
});
test('远端工具版本、同一Rust及Clang对象和完整构建选项不能替换', context => {
  const f = fixture(context), rust = join(f.work, 'tools/rust'), node = join(f.work, 'tools/node'), clang = join(f.work, 'tools/llvm/bin/clang');
  const cmake = join(f.work, 'tools/cmake'), libclang = join(f.work, 'tools/llvm/lib');
  const input = { CARGO: join(rust, 'bin/cargo'), TATAGATE_CARGO: join(rust, 'bin/cargo'), RUSTC: join(rust, 'bin/rustc'),
    TATAGATE_RUSTC: join(rust, 'bin/rustc'), RUSTDOC: join(rust, 'bin/rustdoc'), TATAGATE_NODE: node, CC: clang,
    CXX: join(f.work, 'tools/llvm/bin/clang++'), CMAKE_COMMAND: cmake, LIBCLANG_PATH: libclang,
    PROTOC: join(f.work, 'tools/protoc/bin/protoc'), PRODUCT_GIT_BIN: join(f.work, 'tools/git/payload/bin/git'),
    TATAGATE_ACTIONLINT: join(f.work, 'tools/actionlint/actionlint'), CARGO_BUILD_JOBS: '2',
    CARGO_PROFILE_DEV_DEBUG: '0', CARGO_PROFILE_TEST_DEBUG: '0', CARGO_INCREMENTAL: '0',
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: '--cfg=rustix_use_libc' };
  const versions = new Map([[node, 'v25.2.1'], [input.CARGO, 'cargo 1.97.1 fixture'], [input.RUSTC, 'rustc 1.97.1 fixture'],
    [input.RUSTDOC, 'rustdoc 1.97.1 fixture'], [clang, 'Ubuntu clang version 18.1.3 fixture'], [cmake, 'cmake version 3.31.6'],
    [input.PROTOC, 'libprotoc 35.0'], [input.PRODUCT_GIT_BIN, 'git version 2.54.0'], [input.TATAGATE_ACTIONLINT, '1.7.12\nbuild info'],
    [join(f.work, 'tools/solidity/bin/solc'), 'solc, the solidity compiler commandline interface\nVersion: 0.8.30+commit.73712a01.Linux.g++'],
    [join(f.work, 'tools/solidity/bin/resolc'), 'Solidity frontend for the revive compiler version 1.0.0+commit.b080c1d.llvm-18.1.8']]);
  for (const path of versions.keys()) { mkdirSync(join(path, '..'), { recursive: true }); writeFileSync(path, 'fixture', { mode: 0o755 }); }
  mkdirSync(libclang, { recursive: true }); writeFileSync(join(libclang, 'libclang.so.1'), 'fixture');
  symlinkSync(clang, input.CXX);
  const options = { execute: tool => versions.get(tool), expectedRust: rust, expectedNode: node, expectedClang: clang, expectedCMake: cmake, expectedLibclang: libclang };
  assert.equal(remoteTools(f.root, f.work, input, options), join(rust, 'lib/rustlib/src/rust/library'));
  for (const key of Object.keys(input)) assert.throws(() => remoteTools(f.root, f.work, { ...input, [key]: 'wrong' }, options), undefined, key);
  const missingFlag = { ...input }; delete missingFlag.CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS;
  assert.throws(() => remoteTools(f.root, f.work, missingFlag, options), /交付不符/u);
  for (const tool of versions.keys()) assert.throws(() => remoteTools(f.root, f.work, input, { ...options, execute: value => value === tool ? '0.0.0' : versions.get(value) }));
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER', 'RUSTUP_TOOLCHAIN',
    'RUSTFLAGS', 'CARGO_ENCODED_RUSTFLAGS']) assert.throws(() => remoteTools(f.root, f.work, { ...input, [key]: '0' }, options), /拒绝/u);
  const hardlink = input.PRODUCT_GIT_BIN + '-hardlink';
  linkSync(input.PRODUCT_GIT_BIN, hardlink);
  assert.throws(() => remoteTools(f.root, f.work, input, options), error =>
    error.message === 'SDK准备文件不是独占普通文件：' + input.PRODUCT_GIT_BIN);
  rmSync(hardlink);
  assert.equal(remoteTools(f.root, f.work, input, options), join(rust, 'lib/rustlib/src/rust/library'));
});
test('远端首次与失败后的补修均覆盖合同初始提交以来的改动，非法区间拒绝', () => {
  const after = 'b'.repeat(40), failed = 'a93ed7b73119fdf4edb512943dba616bd9d53ba1';
  for (const before of [contract.initial_sha, failed]) {
    assert.deepEqual(remoteRange(contract, { before, after }), { base: contract.initial_sha, head: after });
  }
  assert.throws(() => remoteRange({ ...contract, checks: [] }, { before: failed, after }));
  for (const event of [{ before: 'main', after }, { before: failed, after: 'main' },
    { before: after, after }, { before: failed, after: contract.initial_sha }]) {
    assert.throws(() => remoteRange(contract, event));
  }
});
test('宿主生成器变更同时触发原生、实际WASM执行器及文档测试，普通改动不增加范围', () => {
  const path = 'substrate/primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs';
  assert.deepEqual(hostChecks(['substrate/frame/revive/src/lib.rs']), []);
  assert.deepEqual(hostChecks([path]), [['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface-test', '--lib'],
    ['test', '--locked', '--offline', '-p', 'sp-runtime-interface', '--doc']]);
});
test('Workflow保留固定官方安装器、只读同SHA push并明确完整准备；没有扩大下载或删除Runner', () => {
  const workflow = readFileSync(new URL('../workflows/tatagate.yml', import.meta.url), 'utf8');
  for (const value of ['timeout-minutes: 240', 'contents: read', 'ref: ${{ github.sha }}', 'persist-credentials: false',
    'node-version: 25.2.1', 'toolchain: 1.97.1', 'components: rustfmt,clippy,rust-src', 'targets: wasm32-unknown-unknown',
    'a0853c24544627f65ddf259abe73b1d18a591444', '032958afbdc797a9164d3bc0b56325c1308924a5',
    '/home/runner/work/_temp/polkadot-sdk-tatagate', 'CARGO_BUILD_JOBS=2', 'CARGO_PROFILE_DEV_DEBUG=0',
    'CARGO_PROFILE_TEST_DEBUG=0', 'CARGO_INCREMENTAL=0', '.github/tatagate/index.mjs prepare', '.github/tatagate/index.mjs remote',
    'CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=--cfg=rustix_use_libc',
    'NO_INSTALL_HARDLINKS=YesPlease', 'test "$(stat -c \'%h\' "$tool/payload/bin/git")" = 1']) assert.ok(workflow.includes(value), value);
  for (const hash of ['c63393dd39d8bc49580e3e23be3eda63ce62ae4823d95f692c7547b25ade8a31',
    '87281ce46d74f261caff4ac404fe5af7b07f185d305246fef81797ddc20fa9f8',
    'f3e987dc6ecebd4bd350c48edcbc320b46cf9e3109bd3fc3d88f1acaf4c428f7',
    'e626ba7a1a0d26828c14713781b0082ececc9a0fbfe984f11f0d93d66bbd7806',
    'a45cda0989c17dd950db55f6fbe1e5814c50fda08e87aa422980ac1f89dddbbc']) assert.ok(workflow.includes(hash));
  assert.doesNotMatch(workflow, /apt-get|apt install|dpkg-deb|NO_CURL|NO_EXPAT|rm -rf|npm (?:ci|install)|SKIP_WASM_BUILD|SKIP_PALLET_REVIVE_FIXTURES/u);
  assert.equal((workflow.match(/https:[^'\n]+\.deb/gu) ?? []).length, 2);
});
test('错仓、错来源、缺检查与非法区间拒绝', () => {
  for (const change of [{ repository: 'citizenchain' }, { upstream: 'other/polkadot-sdk' }, { checks: [] }, { upstream_base: 'main' }, { schema: 2 }]) {
    assert.throws(() => gateContract({ ...contract, ...change }));
  }
  for (const pair of [['a', 'b'], ['a'.repeat(40), 'a'.repeat(40)], [null, 'b'.repeat(40)], ['A'.repeat(40), 'b'.repeat(40)]]) {
    assert.throws(() => gateRange(...pair));
  }
});
test('绝对路径、空段及路径穿越拒绝', () => {
  for (const path of ['', '/substrate/lib.rs', '../lib.rs', 'a/../b', 'a//b', 'a\\b']) assert.throws(() => gatePath(path));
});

test('真实离线子Cargo拒绝父cfg泄漏，WASM命令隔离后按自身目标重新生成', context => {
  const cargo = process.env.TATAGATE_CARGO, rustc = process.env.TATAGATE_RUSTC;
  assert.ok(cargo?.startsWith('/') && rustc?.startsWith('/'), '回归需要SDK公开交付的同一Rust对象');
  assert.equal(realpathSync(cargo), cargo); assert.equal(realpathSync(rustc), rustc);
  assert.equal(dirname(cargo), dirname(rustc));
  for (const [tool, expected] of [[cargo, 'cargo 1.97.1 '], [rustc, 'rustc 1.97.1 ']]) {
    const result = spawnSync(tool, ['--version'], { encoding: 'utf8', timeout: 10_000 });
    assert.equal(result.status, 0); assert.ok(result.stdout.startsWith(expected));
  }
  const source = readFileSync(new URL('../../substrate/utils/wasm-builder/src/wasm_project.rs', import.meta.url), 'utf8');
  assert.match(source, /\.env_remove\("CARGO_ENCODED_RUSTFLAGS"\)[\s\S]*?\.env_remove\("CARGO_CFG_RUSTIX_USE_LIBC"\)[\s\S]*?\.env_remove\("RUSTC"\)/u);
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-child-cargo-cfg-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  mkdirSync(join(directory, 'src')); mkdirSync(join(directory, 'home'));
  const manifest = '[package]\nname = "sdk-child-cargo-cfg"\nversion = "0.1.0"\nedition = "2021"\n[workspace]\n';
  const frozenLock = 'version = 4\n\n[[package]]\nname = "sdk-child-cargo-cfg"\nversion = "0.1.0"\n';
  writeFileSync(join(directory, 'Cargo.toml'), manifest); writeFileSync(join(directory, 'Cargo.lock'), frozenLock);
  writeFileSync(join(directory, 'src/lib.rs'), '#![no_std]\n');
  // 零外部依赖的真实构建脚本独立比较环境与编译cfg，不能以字符串断言代替子Cargo行为。
  writeFileSync(join(directory, 'build.rs'), 'fn main() { assert_eq!(std::env::var_os("CARGO_CFG_RUSTIX_USE_LIBC").is_some(), cfg!(rustix_use_libc), "父cfg泄漏到子Cargo"); }\n');
  for (const inherited of [true, false]) {
    const environment = { PATH: process.env.PATH, CARGO_HOME: join(directory, 'home'), CARGO_NET_OFFLINE: 'true',
      CARGO_TARGET_DIR: join(directory, inherited ? 'leaked-target' : 'isolated-target'),
      RUSTC: rustc, CARGO: cargo, RUSTFLAGS: '', RUSTC_BOOTSTRAP: '1' };
    if (inherited) environment.CARGO_CFG_RUSTIX_USE_LIBC = '';
    const result = spawnSync(cargo, ['check', '--locked', '--offline', '--target', 'wasm32-unknown-unknown'],
      { cwd: directory, env: environment, encoding: 'utf8', timeout: 60_000 });
    assert.equal(result.error, undefined);
    assert.equal(result.status, inherited ? 101 : 0, result.stderr);
    assert.equal(result.stderr.includes('panicked at') && result.stderr.includes('父cfg泄漏到子Cargo'), inherited);
    assert.equal(readFileSync(join(directory, 'Cargo.lock'), 'utf8'), frozenLock);
  }
});

test('完整门禁使用同一Rust对象和独立离线环境，拒绝跳过及工具替换', context => {
  const directory = realpathSync(mkdtempSync(join(tmpdir(), 'sdk-gate-environment-')));
  context.after(() => rmSync(directory, { recursive: true, force: true }));
  const root = join(directory, 'repository'), work = join(directory, 'gate');
  const home = join(directory, 'cargo/home'), packages = join(directory, 'cargo/packages');
  const bin = join(directory, 'rust/bin');
  for (const path of [root, work, home, packages, bin]) mkdirSync(path, { recursive: true });
  for (const tool of ['cargo', 'rustc']) writeFileSync(join(bin, tool), 'fixture', { mode: 0o755 });
  const config = '[net]\noffline = true\n\n[source.crates-io]\nreplace-with = "verified"\n\n[source.verified]\ndirectory = '
    + JSON.stringify(packages) + '\n';
  writeFileSync(join(home, 'config.toml'), config);
  const input = { TATAGATE_CARGO: join(bin, 'cargo'), TATAGATE_RUSTC: join(bin, 'rustc'),
    CARGO: join(bin, 'cargo'), RUSTC: join(bin, 'rustc'), CARGO_HOME: home };
  const execute = tool => tool.endsWith('/cargo') ? 'cargo 1.97.1 fixture' : 'rustc 1.97.1 fixture';
  const result = gateEnvironment(root, work, input, { execute });
  assert.equal(result.CARGO_NET_OFFLINE, 'true'); assert.equal(result.CARGO_TARGET_DIR, join(work, 'cargo-target'));
  assert.equal(result.RUSTC, input.RUSTC); assert.equal(result.WASM_BUILD_STD, '1');
  assert.equal(result.WASM_BUILD_WORKSPACE_HINT, root);
  assert.equal(gateEnvironment(root, work, { ...input, WASM_BUILD_WORKSPACE_HINT: '/other/repository' },
    { execute }).WASM_BUILD_WORKSPACE_HINT, root);
  for (const key of ['SKIP_PALLET_REVIVE_FIXTURES', 'SKIP_WASM_BUILD', 'RUSTC_WRAPPER', 'RUSTUP_TOOLCHAIN']) {
    assert.throws(() => gateEnvironment(root, work, { ...input, [key]: '0' }, { execute }), /拒绝/u);
  }
  for (const changes of [{ RUSTC: '/other/rustc' }, { CARGO: '/other/cargo' }, { CARGO_HOME: root }]) {
    assert.throws(() => gateEnvironment(root, work, { ...input, ...changes }, { execute }));
  }
  assert.throws(() => gateEnvironment(root, root, input, { execute }), /中间物/u);
  assert.throws(() => gateEnvironment(root, work, input, { execute: () => 'rustc 1.97.0 fixture' }), /版本/u);
  symlinkSync(home, join(directory, 'home-link'));
  assert.throws(() => gateEnvironment(root, work, { ...input, CARGO_HOME: join(directory, 'home-link') }, { execute }));
  writeFileSync(join(home, 'config.toml'), config.replace('offline = true', 'offline = false'));
  assert.throws(() => gateEnvironment(root, work, input, { execute }), /目录源/u);
});
